// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/primelib/komga-client/sdk/go/pkgs/operations"
)

type FileSystemControllerService Service

// PostFilesystemV1
//
//meta:operation POST /api/v1/filesystem
func (s *FileSystemControllerService) PostFilesystemV1(ctx context.Context, req operations.PostFilesystemV1Request) (*operations.PostFilesystemV1Response, error) {
	return operations.PostFilesystemV1(s.client.restyClient, ctx, req)
}
