// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/primelib/komga-client/sdk/go/pkgs/operations"
)

type TransientBooksControllerService Service

// PostTransientBooksV1
//
//meta:operation POST /api/v1/transient-books
func (s *TransientBooksControllerService) PostTransientBooksV1(ctx context.Context, req operations.PostTransientBooksV1Request) (*operations.PostTransientBooksV1Response, error) {
	return operations.PostTransientBooksV1(s.client.restyClient, ctx, req)
}

// PostTransientBookByIDAnalyzeV1
//
//meta:operation POST /api/v1/transient-books/{id}/analyze
func (s *TransientBooksControllerService) PostTransientBookByIDAnalyzeV1(ctx context.Context, req operations.PostTransientBookByIDAnalyzeV1Request) (*operations.PostTransientBookByIDAnalyzeV1Response, error) {
	return operations.PostTransientBookByIDAnalyzeV1(s.client.restyClient, ctx, req)
}

// GetTransientBookByIDPageByPageNumberV1
//
//meta:operation GET /api/v1/transient-books/{id}/pages/{pageNumber}
func (s *TransientBooksControllerService) GetTransientBookByIDPageByPageNumberV1(ctx context.Context, req operations.GetTransientBookByIDPageByPageNumberV1Request) (*operations.GetTransientBookByIDPageByPageNumberV1Response, error) {
	return operations.GetTransientBookByIDPageByPageNumberV1(s.client.restyClient, ctx, req)
}
