// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/primelib/komga-client/sdk/go/pkgs/operations"
)

type OAuth2ControllerService Service

// GetOauth2ProvIDErsV1
//
//meta:operation GET /api/v1/oauth2/providers
func (s *OAuth2ControllerService) GetOauth2ProvIDErsV1(ctx context.Context, req operations.GetOauth2ProvIDErsV1Request) (*operations.GetOauth2ProvIDErsV1Response, error) {
	return operations.GetOauth2ProvIDErsV1(s.client.restyClient, ctx, req)
}

// PutOauth2ProvIDErsV1
//
//meta:operation PUT /api/v1/oauth2/providers
func (s *OAuth2ControllerService) PutOauth2ProvIDErsV1(ctx context.Context, req operations.PutOauth2ProvIDErsV1Request) (*operations.PutOauth2ProvIDErsV1Response, error) {
	return operations.PutOauth2ProvIDErsV1(s.client.restyClient, ctx, req)
}

// PostOauth2ProvIDErsV1
//
//meta:operation POST /api/v1/oauth2/providers
func (s *OAuth2ControllerService) PostOauth2ProvIDErsV1(ctx context.Context, req operations.PostOauth2ProvIDErsV1Request) (*operations.PostOauth2ProvIDErsV1Response, error) {
	return operations.PostOauth2ProvIDErsV1(s.client.restyClient, ctx, req)
}

// DeleteOauth2ProvIDErsV1
//
//meta:operation DELETE /api/v1/oauth2/providers
func (s *OAuth2ControllerService) DeleteOauth2ProvIDErsV1(ctx context.Context, req operations.DeleteOauth2ProvIDErsV1Request) (*operations.DeleteOauth2ProvIDErsV1Response, error) {
	return operations.DeleteOauth2ProvIDErsV1(s.client.restyClient, ctx, req)
}

// OptionsOauth2ProvIDErsV1
//
//meta:operation OPTIONS /api/v1/oauth2/providers
func (s *OAuth2ControllerService) OptionsOauth2ProvIDErsV1(ctx context.Context, req operations.OptionsOauth2ProvIDErsV1Request) (*operations.OptionsOauth2ProvIDErsV1Response, error) {
	return operations.OptionsOauth2ProvIDErsV1(s.client.restyClient, ctx, req)
}

// HeadOauth2ProvIDErsV1
//
//meta:operation HEAD /api/v1/oauth2/providers
func (s *OAuth2ControllerService) HeadOauth2ProvIDErsV1(ctx context.Context, req operations.HeadOauth2ProvIDErsV1Request) (*operations.HeadOauth2ProvIDErsV1Response, error) {
	return operations.HeadOauth2ProvIDErsV1(s.client.restyClient, ctx, req)
}

// PatchOauth2ProvIDErsV1
//
//meta:operation PATCH /api/v1/oauth2/providers
func (s *OAuth2ControllerService) PatchOauth2ProvIDErsV1(ctx context.Context, req operations.PatchOauth2ProvIDErsV1Request) (*operations.PatchOauth2ProvIDErsV1Response, error) {
	return operations.PatchOauth2ProvIDErsV1(s.client.restyClient, ctx, req)
}
