// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/primelib/komga-client/sdk/go/pkgs/operations"
)

type OpdsCommonControllerService Service

// GetOpdsV12BookByBookIDThumbnailV1
//
//meta:operation GET /opds/v1.2/books/{bookId}/thumbnail
func (s *OpdsCommonControllerService) GetOpdsV12BookByBookIDThumbnailV1(ctx context.Context, req operations.GetOpdsV12BookByBookIDThumbnailV1Request) (*operations.GetOpdsV12BookByBookIDThumbnailV1Response, error) {
	return operations.GetOpdsV12BookByBookIDThumbnailV1(s.client.restyClient, ctx, req)
}

// GetOpdsbookByBookIDThumbnailV2
//
//meta:operation GET /opds/v2/books/{bookId}/thumbnail
func (s *OpdsCommonControllerService) GetOpdsbookByBookIDThumbnailV2(ctx context.Context, req operations.GetOpdsbookByBookIDThumbnailV2Request) (*operations.GetOpdsbookByBookIDThumbnailV2Response, error) {
	return operations.GetOpdsbookByBookIDThumbnailV2(s.client.restyClient, ctx, req)
}
