// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/primelib/komga-client/sdk/go/pkgs/operations"
)

type SeriesCollectionControllerService Service

// PutCollectionByIDThumbnailByThumbnailIDSelectedV1
//
//meta:operation PUT /api/v1/collections/{id}/thumbnails/{thumbnailId}/selected
func (s *SeriesCollectionControllerService) PutCollectionByIDThumbnailByThumbnailIDSelectedV1(ctx context.Context, req operations.PutCollectionByIDThumbnailByThumbnailIDSelectedV1Request) (*operations.PutCollectionByIDThumbnailByThumbnailIDSelectedV1Response, error) {
	return operations.PutCollectionByIDThumbnailByThumbnailIDSelectedV1(s.client.restyClient, ctx, req)
}

// GetCollectionsV1
//
//meta:operation GET /api/v1/collections
func (s *SeriesCollectionControllerService) GetCollectionsV1(ctx context.Context, req operations.GetCollectionsV1Request) (*operations.GetCollectionsV1Response, error) {
	return operations.GetCollectionsV1(s.client.restyClient, ctx, req)
}

// PostCollectionsV1
//
//meta:operation POST /api/v1/collections
func (s *SeriesCollectionControllerService) PostCollectionsV1(ctx context.Context, req operations.PostCollectionsV1Request) (*operations.PostCollectionsV1Response, error) {
	return operations.PostCollectionsV1(s.client.restyClient, ctx, req)
}

// GetCollectionByIDThumbnailsV1
//
//meta:operation GET /api/v1/collections/{id}/thumbnails
func (s *SeriesCollectionControllerService) GetCollectionByIDThumbnailsV1(ctx context.Context, req operations.GetCollectionByIDThumbnailsV1Request) (*operations.GetCollectionByIDThumbnailsV1Response, error) {
	return operations.GetCollectionByIDThumbnailsV1(s.client.restyClient, ctx, req)
}

// PostCollectionByIDThumbnailsV1
//
//meta:operation POST /api/v1/collections/{id}/thumbnails
func (s *SeriesCollectionControllerService) PostCollectionByIDThumbnailsV1(ctx context.Context, req operations.PostCollectionByIDThumbnailsV1Request) (*operations.PostCollectionByIDThumbnailsV1Response, error) {
	return operations.PostCollectionByIDThumbnailsV1(s.client.restyClient, ctx, req)
}

// GetCollectionByIDV1
//
//meta:operation GET /api/v1/collections/{id}
func (s *SeriesCollectionControllerService) GetCollectionByIDV1(ctx context.Context, req operations.GetCollectionByIDV1Request) (*operations.GetCollectionByIDV1Response, error) {
	return operations.GetCollectionByIDV1(s.client.restyClient, ctx, req)
}

// DeleteCollectionByIDV1
//
//meta:operation DELETE /api/v1/collections/{id}
func (s *SeriesCollectionControllerService) DeleteCollectionByIDV1(ctx context.Context, req operations.DeleteCollectionByIDV1Request) (*operations.DeleteCollectionByIDV1Response, error) {
	return operations.DeleteCollectionByIDV1(s.client.restyClient, ctx, req)
}

// PatchCollectionByIDV1
//
//meta:operation PATCH /api/v1/collections/{id}
func (s *SeriesCollectionControllerService) PatchCollectionByIDV1(ctx context.Context, req operations.PatchCollectionByIDV1Request) (*operations.PatchCollectionByIDV1Response, error) {
	return operations.PatchCollectionByIDV1(s.client.restyClient, ctx, req)
}

// GetCollectionByIDThumbnailByThumbnailIDV1
//
//meta:operation GET /api/v1/collections/{id}/thumbnails/{thumbnailId}
func (s *SeriesCollectionControllerService) GetCollectionByIDThumbnailByThumbnailIDV1(ctx context.Context, req operations.GetCollectionByIDThumbnailByThumbnailIDV1Request) (*operations.GetCollectionByIDThumbnailByThumbnailIDV1Response, error) {
	return operations.GetCollectionByIDThumbnailByThumbnailIDV1(s.client.restyClient, ctx, req)
}

// DeleteCollectionByIDThumbnailByThumbnailIDV1
//
//meta:operation DELETE /api/v1/collections/{id}/thumbnails/{thumbnailId}
func (s *SeriesCollectionControllerService) DeleteCollectionByIDThumbnailByThumbnailIDV1(ctx context.Context, req operations.DeleteCollectionByIDThumbnailByThumbnailIDV1Request) (*operations.DeleteCollectionByIDThumbnailByThumbnailIDV1Response, error) {
	return operations.DeleteCollectionByIDThumbnailByThumbnailIDV1(s.client.restyClient, ctx, req)
}

// GetCollectionByIDThumbnailV1
//
//meta:operation GET /api/v1/collections/{id}/thumbnail
func (s *SeriesCollectionControllerService) GetCollectionByIDThumbnailV1(ctx context.Context, req operations.GetCollectionByIDThumbnailV1Request) (*operations.GetCollectionByIDThumbnailV1Response, error) {
	return operations.GetCollectionByIDThumbnailV1(s.client.restyClient, ctx, req)
}

// GetCollectionByIDSeriesV1
//
//meta:operation GET /api/v1/collections/{id}/series
func (s *SeriesCollectionControllerService) GetCollectionByIDSeriesV1(ctx context.Context, req operations.GetCollectionByIDSeriesV1Request) (*operations.GetCollectionByIDSeriesV1Response, error) {
	return operations.GetCollectionByIDSeriesV1(s.client.restyClient, ctx, req)
}
