// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/primelib/komga-client/sdk/go/pkgs/operations"
)

type ClaimControllerService Service

// GetClaimV1
//
//meta:operation GET /api/v1/claim
func (s *ClaimControllerService) GetClaimV1(ctx context.Context, req operations.GetClaimV1Request) (*operations.GetClaimV1Response, error) {
	return operations.GetClaimV1(s.client.restyClient, ctx, req)
}

// PostClaimV1
//
//meta:operation POST /api/v1/claim
func (s *ClaimControllerService) PostClaimV1(ctx context.Context, req operations.PostClaimV1Request) (*operations.PostClaimV1Response, error) {
	return operations.PostClaimV1(s.client.restyClient, ctx, req)
}
