// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/primelib/komga-client/sdk/go/pkgs/operations"
)

type UserControllerService Service

// GetUsersV2
//
//meta:operation GET /api/v2/users
func (s *UserControllerService) GetUsersV2(ctx context.Context, req operations.GetUsersV2Request) (*operations.GetUsersV2Response, error) {
	return operations.GetUsersV2(s.client.restyClient, ctx, req)
}

// PostUsersV2
//
//meta:operation POST /api/v2/users
func (s *UserControllerService) PostUsersV2(ctx context.Context, req operations.PostUsersV2Request) (*operations.PostUsersV2Response, error) {
	return operations.PostUsersV2(s.client.restyClient, ctx, req)
}

// DeleteUserByIDV2
//
//meta:operation DELETE /api/v2/users/{id}
func (s *UserControllerService) DeleteUserByIDV2(ctx context.Context, req operations.DeleteUserByIDV2Request) (*operations.DeleteUserByIDV2Response, error) {
	return operations.DeleteUserByIDV2(s.client.restyClient, ctx, req)
}

// PatchUserByIDV2
//
//meta:operation PATCH /api/v2/users/{id}
func (s *UserControllerService) PatchUserByIDV2(ctx context.Context, req operations.PatchUserByIDV2Request) (*operations.PatchUserByIDV2Response, error) {
	return operations.PatchUserByIDV2(s.client.restyClient, ctx, req)
}

// PatchUserByIDPasswordV2
//
//meta:operation PATCH /api/v2/users/{id}/password
func (s *UserControllerService) PatchUserByIDPasswordV2(ctx context.Context, req operations.PatchUserByIDPasswordV2Request) (*operations.PatchUserByIDPasswordV2Response, error) {
	return operations.PatchUserByIDPasswordV2(s.client.restyClient, ctx, req)
}

// PatchUsersMePasswordV2
//
//meta:operation PATCH /api/v2/users/me/password
func (s *UserControllerService) PatchUsersMePasswordV2(ctx context.Context, req operations.PatchUsersMePasswordV2Request) (*operations.PatchUsersMePasswordV2Response, error) {
	return operations.PatchUsersMePasswordV2(s.client.restyClient, ctx, req)
}

// GetUserByIDAuthenticationActivityLatestV2
//
//meta:operation GET /api/v2/users/{id}/authentication-activity/latest
func (s *UserControllerService) GetUserByIDAuthenticationActivityLatestV2(ctx context.Context, req operations.GetUserByIDAuthenticationActivityLatestV2Request) (*operations.GetUserByIDAuthenticationActivityLatestV2Response, error) {
	return operations.GetUserByIDAuthenticationActivityLatestV2(s.client.restyClient, ctx, req)
}

// GetUsersMeV2
//
//meta:operation GET /api/v2/users/me
func (s *UserControllerService) GetUsersMeV2(ctx context.Context, req operations.GetUsersMeV2Request) (*operations.GetUsersMeV2Response, error) {
	return operations.GetUsersMeV2(s.client.restyClient, ctx, req)
}

// GetUsersMeAuthenticationActivityV2
//
//meta:operation GET /api/v2/users/me/authentication-activity
func (s *UserControllerService) GetUsersMeAuthenticationActivityV2(ctx context.Context, req operations.GetUsersMeAuthenticationActivityV2Request) (*operations.GetUsersMeAuthenticationActivityV2Response, error) {
	return operations.GetUsersMeAuthenticationActivityV2(s.client.restyClient, ctx, req)
}

// GetUsersAuthenticationActivityV2
//
//meta:operation GET /api/v2/users/authentication-activity
func (s *UserControllerService) GetUsersAuthenticationActivityV2(ctx context.Context, req operations.GetUsersAuthenticationActivityV2Request) (*operations.GetUsersAuthenticationActivityV2Response, error) {
	return operations.GetUsersAuthenticationActivityV2(s.client.restyClient, ctx, req)
}
