// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/primelib/komga-client/sdk/go/pkgs/operations"
)

type SeriesControllerService Service

// GetSeriesBySeriesIDReadProgressTachiyomiV2
//
//meta:operation GET /api/v2/series/{seriesId}/read-progress/tachiyomi
func (s *SeriesControllerService) GetSeriesBySeriesIDReadProgressTachiyomiV2(ctx context.Context, req operations.GetSeriesBySeriesIDReadProgressTachiyomiV2Request) (*operations.GetSeriesBySeriesIDReadProgressTachiyomiV2Response, error) {
	return operations.GetSeriesBySeriesIDReadProgressTachiyomiV2(s.client.restyClient, ctx, req)
}

// PutSeriesBySeriesIDReadProgressTachiyomiV2
//
//meta:operation PUT /api/v2/series/{seriesId}/read-progress/tachiyomi
func (s *SeriesControllerService) PutSeriesBySeriesIDReadProgressTachiyomiV2(ctx context.Context, req operations.PutSeriesBySeriesIDReadProgressTachiyomiV2Request) (*operations.PutSeriesBySeriesIDReadProgressTachiyomiV2Response, error) {
	return operations.PutSeriesBySeriesIDReadProgressTachiyomiV2(s.client.restyClient, ctx, req)
}

// PutSeriesBySeriesIDThumbnailByThumbnailIDSelectedV1
//
//meta:operation PUT /api/v1/series/{seriesId}/thumbnails/{thumbnailId}/selected
func (s *SeriesControllerService) PutSeriesBySeriesIDThumbnailByThumbnailIDSelectedV1(ctx context.Context, req operations.PutSeriesBySeriesIDThumbnailByThumbnailIDSelectedV1Request) (*operations.PutSeriesBySeriesIDThumbnailByThumbnailIDSelectedV1Response, error) {
	return operations.PutSeriesBySeriesIDThumbnailByThumbnailIDSelectedV1(s.client.restyClient, ctx, req)
}

// GetSeriesBySeriesIDThumbnailsV1
//
//meta:operation GET /api/v1/series/{seriesId}/thumbnails
func (s *SeriesControllerService) GetSeriesBySeriesIDThumbnailsV1(ctx context.Context, req operations.GetSeriesBySeriesIDThumbnailsV1Request) (*operations.GetSeriesBySeriesIDThumbnailsV1Response, error) {
	return operations.GetSeriesBySeriesIDThumbnailsV1(s.client.restyClient, ctx, req)
}

// PostSeriesBySeriesIDThumbnailsV1
//
//meta:operation POST /api/v1/series/{seriesId}/thumbnails
func (s *SeriesControllerService) PostSeriesBySeriesIDThumbnailsV1(ctx context.Context, req operations.PostSeriesBySeriesIDThumbnailsV1Request) (*operations.PostSeriesBySeriesIDThumbnailsV1Response, error) {
	return operations.PostSeriesBySeriesIDThumbnailsV1(s.client.restyClient, ctx, req)
}

// PostSeriesBySeriesIDReadProgressV1 Mark all book for series as read
//
//meta:operation POST /api/v1/series/{seriesId}/read-progress
func (s *SeriesControllerService) PostSeriesBySeriesIDReadProgressV1(ctx context.Context, req operations.PostSeriesBySeriesIDReadProgressV1Request) (*operations.PostSeriesBySeriesIDReadProgressV1Response, error) {
	return operations.PostSeriesBySeriesIDReadProgressV1(s.client.restyClient, ctx, req)
}

// DeleteSeriesBySeriesIDReadProgressV1 Mark all book for series as unread
//
//meta:operation DELETE /api/v1/series/{seriesId}/read-progress
func (s *SeriesControllerService) DeleteSeriesBySeriesIDReadProgressV1(ctx context.Context, req operations.DeleteSeriesBySeriesIDReadProgressV1Request) (*operations.DeleteSeriesBySeriesIDReadProgressV1Response, error) {
	return operations.DeleteSeriesBySeriesIDReadProgressV1(s.client.restyClient, ctx, req)
}

// PostSeriesBySeriesIDMetadataRefreshV1
//
//meta:operation POST /api/v1/series/{seriesId}/metadata/refresh
func (s *SeriesControllerService) PostSeriesBySeriesIDMetadataRefreshV1(ctx context.Context, req operations.PostSeriesBySeriesIDMetadataRefreshV1Request) (*operations.PostSeriesBySeriesIDMetadataRefreshV1Response, error) {
	return operations.PostSeriesBySeriesIDMetadataRefreshV1(s.client.restyClient, ctx, req)
}

// PostSeriesBySeriesIDAnalyzeV1
//
//meta:operation POST /api/v1/series/{seriesId}/analyze
func (s *SeriesControllerService) PostSeriesBySeriesIDAnalyzeV1(ctx context.Context, req operations.PostSeriesBySeriesIDAnalyzeV1Request) (*operations.PostSeriesBySeriesIDAnalyzeV1Response, error) {
	return operations.PostSeriesBySeriesIDAnalyzeV1(s.client.restyClient, ctx, req)
}

// PatchSeriesBySeriesIDMetadataV1
//
//meta:operation PATCH /api/v1/series/{seriesId}/metadata
func (s *SeriesControllerService) PatchSeriesBySeriesIDMetadataV1(ctx context.Context, req operations.PatchSeriesBySeriesIDMetadataV1Request) (*operations.PatchSeriesBySeriesIDMetadataV1Response, error) {
	return operations.PatchSeriesBySeriesIDMetadataV1(s.client.restyClient, ctx, req)
}

// GetSeriesV1
//
//meta:operation GET /api/v1/series
func (s *SeriesControllerService) GetSeriesV1(ctx context.Context, req operations.GetSeriesV1Request) (*operations.GetSeriesV1Response, error) {
	return operations.GetSeriesV1(s.client.restyClient, ctx, req)
}

// GetSeriesBySeriesIDV1
//
//meta:operation GET /api/v1/series/{seriesId}
func (s *SeriesControllerService) GetSeriesBySeriesIDV1(ctx context.Context, req operations.GetSeriesBySeriesIDV1Request) (*operations.GetSeriesBySeriesIDV1Response, error) {
	return operations.GetSeriesBySeriesIDV1(s.client.restyClient, ctx, req)
}

// GetSeriesBySeriesIDThumbnailByThumbnailIDV1
//
//meta:operation GET /api/v1/series/{seriesId}/thumbnails/{thumbnailId}
func (s *SeriesControllerService) GetSeriesBySeriesIDThumbnailByThumbnailIDV1(ctx context.Context, req operations.GetSeriesBySeriesIDThumbnailByThumbnailIDV1Request) (*operations.GetSeriesBySeriesIDThumbnailByThumbnailIDV1Response, error) {
	return operations.GetSeriesBySeriesIDThumbnailByThumbnailIDV1(s.client.restyClient, ctx, req)
}

// DeleteSeriesBySeriesIDThumbnailByThumbnailIDV1
//
//meta:operation DELETE /api/v1/series/{seriesId}/thumbnails/{thumbnailId}
func (s *SeriesControllerService) DeleteSeriesBySeriesIDThumbnailByThumbnailIDV1(ctx context.Context, req operations.DeleteSeriesBySeriesIDThumbnailByThumbnailIDV1Request) (*operations.DeleteSeriesBySeriesIDThumbnailByThumbnailIDV1Response, error) {
	return operations.DeleteSeriesBySeriesIDThumbnailByThumbnailIDV1(s.client.restyClient, ctx, req)
}

// GetSeriesBySeriesIDThumbnailV1
//
//meta:operation GET /api/v1/series/{seriesId}/thumbnail
func (s *SeriesControllerService) GetSeriesBySeriesIDThumbnailV1(ctx context.Context, req operations.GetSeriesBySeriesIDThumbnailV1Request) (*operations.GetSeriesBySeriesIDThumbnailV1Response, error) {
	return operations.GetSeriesBySeriesIDThumbnailV1(s.client.restyClient, ctx, req)
}

// GetSeriesBySeriesIDFileV1
//
//meta:operation GET /api/v1/series/{seriesId}/file
func (s *SeriesControllerService) GetSeriesBySeriesIDFileV1(ctx context.Context, req operations.GetSeriesBySeriesIDFileV1Request) (*operations.GetSeriesBySeriesIDFileV1Response, error) {
	return operations.GetSeriesBySeriesIDFileV1(s.client.restyClient, ctx, req)
}

// DeleteSeriesBySeriesIDFileV1
//
//meta:operation DELETE /api/v1/series/{seriesId}/file
func (s *SeriesControllerService) DeleteSeriesBySeriesIDFileV1(ctx context.Context, req operations.DeleteSeriesBySeriesIDFileV1Request) (*operations.DeleteSeriesBySeriesIDFileV1Response, error) {
	return operations.DeleteSeriesBySeriesIDFileV1(s.client.restyClient, ctx, req)
}

// GetSeriesBySeriesIDCollectionsV1
//
//meta:operation GET /api/v1/series/{seriesId}/collections
func (s *SeriesControllerService) GetSeriesBySeriesIDCollectionsV1(ctx context.Context, req operations.GetSeriesBySeriesIDCollectionsV1Request) (*operations.GetSeriesBySeriesIDCollectionsV1Response, error) {
	return operations.GetSeriesBySeriesIDCollectionsV1(s.client.restyClient, ctx, req)
}

// GetSeriesBySeriesIDBooksV1
//
//meta:operation GET /api/v1/series/{seriesId}/books
func (s *SeriesControllerService) GetSeriesBySeriesIDBooksV1(ctx context.Context, req operations.GetSeriesBySeriesIDBooksV1Request) (*operations.GetSeriesBySeriesIDBooksV1Response, error) {
	return operations.GetSeriesBySeriesIDBooksV1(s.client.restyClient, ctx, req)
}

// GetSeriesUpdatedV1 Return recently updated series, but not newly added ones.
//
//meta:operation GET /api/v1/series/updated
func (s *SeriesControllerService) GetSeriesUpdatedV1(ctx context.Context, req operations.GetSeriesUpdatedV1Request) (*operations.GetSeriesUpdatedV1Response, error) {
	return operations.GetSeriesUpdatedV1(s.client.restyClient, ctx, req)
}

// GetSeriesNewV1 Return newly added series.
//
//meta:operation GET /api/v1/series/new
func (s *SeriesControllerService) GetSeriesNewV1(ctx context.Context, req operations.GetSeriesNewV1Request) (*operations.GetSeriesNewV1Response, error) {
	return operations.GetSeriesNewV1(s.client.restyClient, ctx, req)
}

// GetSeriesLatestV1 Return recently added or updated series.
//
//meta:operation GET /api/v1/series/latest
func (s *SeriesControllerService) GetSeriesLatestV1(ctx context.Context, req operations.GetSeriesLatestV1Request) (*operations.GetSeriesLatestV1Response, error) {
	return operations.GetSeriesLatestV1(s.client.restyClient, ctx, req)
}

// GetSeriesAlphabeticalGroupsV1
//
//meta:operation GET /api/v1/series/alphabetical-groups
func (s *SeriesControllerService) GetSeriesAlphabeticalGroupsV1(ctx context.Context, req operations.GetSeriesAlphabeticalGroupsV1Request) (*operations.GetSeriesAlphabeticalGroupsV1Response, error) {
	return operations.GetSeriesAlphabeticalGroupsV1(s.client.restyClient, ctx, req)
}
