// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/primelib/komga-client/sdk/go/pkgs/operations"
)

type LoginControllerService Service

// GetLoginSetCookieV1
//
//meta:operation GET /api/v1/login/set-cookie
func (s *LoginControllerService) GetLoginSetCookieV1(ctx context.Context, req operations.GetLoginSetCookieV1Request) (*operations.GetLoginSetCookieV1Response, error) {
	return operations.GetLoginSetCookieV1(s.client.restyClient, ctx, req)
}
