// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/primelib/komga-client/sdk/go/pkgs/operations"
)

type AnnouncementControllerService Service

// GetAnnouncementsV1
//
//meta:operation GET /api/v1/announcements
func (s *AnnouncementControllerService) GetAnnouncementsV1(ctx context.Context, req operations.GetAnnouncementsV1Request) (*operations.GetAnnouncementsV1Response, error) {
	return operations.GetAnnouncementsV1(s.client.restyClient, ctx, req)
}

// PutAnnouncementsV1
//
//meta:operation PUT /api/v1/announcements
func (s *AnnouncementControllerService) PutAnnouncementsV1(ctx context.Context, req operations.PutAnnouncementsV1Request) (*operations.PutAnnouncementsV1Response, error) {
	return operations.PutAnnouncementsV1(s.client.restyClient, ctx, req)
}
