// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/primelib/komga-client/sdk/go/pkgs/operations"
)

type TaskControllerService Service

// DeleteTasksV1
//
//meta:operation DELETE /api/v1/tasks
func (s *TaskControllerService) DeleteTasksV1(ctx context.Context, req operations.DeleteTasksV1Request) (*operations.DeleteTasksV1Response, error) {
	return operations.DeleteTasksV1(s.client.restyClient, ctx, req)
}
