// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

plugins {
    `java-library`
    alias(libs.plugins.configuration)
}

val version: String = properties["version"] as? String ?: "0.0.0"

projectConfiguration {
    type.set(me.philippheuer.projectcfg.domain.ProjectType.LIBRARY)
    javaVersion.set(JavaVersion.VERSION_17)
    artifactGroupId.set("io.github.primelib")
    artifactId.set("komga-client")
    artifactDisplayName.set("Komga Client")
    artifactDescription.set("This is the API specification for the Komga API.")

    pom = { pom ->
        pom.licenses {
            license {
                name.set("MIT")
                distribution.set("repo")
                url.set("https://github.com/primelib/komga-client/blob/main/LICENSE")
            }
        }
    }
}

dependencies {
    // bom
    api(platform(libs.openFeignBom))
    api(platform(libs.resilience4jBom))
    api(platform(libs.jacksonBom))
    api(platform(libs.micrometerBom))
    api(platform(libs.slf4jBom))
    api(platform(libs.primecodegenlibJavaBom))

    // annotations
    implementation(libs.jspecify)
    implementation(libs.jetbrainsAnnotations)

    // feign
    implementation("io.github.openfeign:feign-core")
    implementation("io.github.openfeign:feign-jackson")
    implementation("io.github.openfeign:feign-slf4j")
    implementation("io.github.openfeign:feign-okhttp")
    implementation("io.github.openfeign:feign-micrometer")

    // http client
    implementation(libs.okhttp)

    // codegen libs
    api("io.github.primelib.primecodegenlib.java:feign-common")

    // jackson
    implementation("com.fasterxml.jackson.core:jackson-databind")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")

    // metrics
    api("io.micrometer:micrometer-core")

    // test
    testImplementation("org.slf4j:slf4j-simple")
}
