// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AgeRestrictionUpdateDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AgeRestrictionUpdateDto")
@JsonPropertyOrder({
    "age",
    "restriction"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AgeRestrictionUpdateDto {

    @JsonProperty("age")
    protected Integer age;

    @JsonProperty("restriction")
    protected String restriction;

    /**
     * Constructs a validated instance of {@link AgeRestrictionUpdateDto}.
     *
     * @param spec the specification to process
     */
    public AgeRestrictionUpdateDto(Consumer<AgeRestrictionUpdateDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AgeRestrictionUpdateDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AgeRestrictionUpdateDto(Consumer)} instead.
     * @param age age
     * @param restriction restriction
     */
    @ApiStatus.Internal
    public AgeRestrictionUpdateDto(Integer age, String restriction) {
        this.age = age;
        this.restriction = restriction;
    }
}
