// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.time.Instant;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AuthenticationActivityDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AuthenticationActivityDto")
@JsonPropertyOrder({
    "userId",
    "email",
    "ip",
    "userAgent",
    "success",
    "error",
    "dateTime",
    "source"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AuthenticationActivityDto {

    @JsonProperty("userId")
    protected String userId;

    @JsonProperty("email")
    protected String email;

    @JsonProperty("ip")
    protected String ip;

    @JsonProperty("userAgent")
    protected String userAgent;

    @JsonProperty("success")
    protected Boolean success;

    @JsonProperty("error")
    protected String error;

    @JsonProperty("dateTime")
    protected java.time.Instant dateTime;

    @JsonProperty("source")
    protected String source;

    /**
     * Constructs a validated instance of {@link AuthenticationActivityDto}.
     *
     * @param spec the specification to process
     */
    public AuthenticationActivityDto(Consumer<AuthenticationActivityDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AuthenticationActivityDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AuthenticationActivityDto(Consumer)} instead.
     * @param userId userId
     * @param email email
     * @param ip ip
     * @param userAgent userAgent
     * @param success success
     * @param error error
     * @param dateTime dateTime
     * @param source source
     */
    @ApiStatus.Internal
    public AuthenticationActivityDto(String userId, String email, String ip, String userAgent, Boolean success, String error, Instant dateTime, String source) {
        this.userId = userId;
        this.email = email;
        this.ip = ip;
        this.userAgent = userAgent;
        this.success = success;
        this.error = error;
        this.dateTime = dateTime;
        this.source = source;
    }
}
