// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AuthorDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AuthorDto")
@JsonPropertyOrder({
    "name",
    "role"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AuthorDto {

    @JsonProperty("name")
    protected String name;

    @JsonProperty("role")
    protected String role;

    /**
     * Constructs a validated instance of {@link AuthorDto}.
     *
     * @param spec the specification to process
     */
    public AuthorDto(Consumer<AuthorDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AuthorDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AuthorDto(Consumer)} instead.
     * @param name name
     * @param role role
     */
    @ApiStatus.Internal
    public AuthorDto(String name, String role) {
        this.name = name;
        this.role = role;
    }
}
