// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.time.Instant;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * BookMetadataUpdateDto
 * <p>
 * Metadata fields to update. Set a field to null to unset the metadata. You can omit fields you don't want to update.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("BookMetadataUpdateDto")
@JsonPropertyOrder({
    "title",
    "titleLock",
    "summaryLock",
    "number",
    "numberLock",
    "numberSort",
    "numberSortLock",
    "releaseDateLock",
    "authorsLock",
    "tagsLock",
    "isbnLock",
    "linksLock",
    "tags",
    "isbn",
    "links",
    "authors",
    "summary",
    "releaseDate"
})
@Generated(value = "io.github.primelib.primecodegen")
public class BookMetadataUpdateDto {

    @JsonProperty("title")
    protected String title;

    @JsonProperty("titleLock")
    protected Boolean titleLock;

    @JsonProperty("summaryLock")
    protected Boolean summaryLock;

    @JsonProperty("number")
    protected String number;

    @JsonProperty("numberLock")
    protected Boolean numberLock;

    @JsonProperty("numberSort")
    protected Float numberSort;

    @JsonProperty("numberSortLock")
    protected Boolean numberSortLock;

    @JsonProperty("releaseDateLock")
    protected Boolean releaseDateLock;

    @JsonProperty("authorsLock")
    protected Boolean authorsLock;

    @JsonProperty("tagsLock")
    protected Boolean tagsLock;

    @JsonProperty("isbnLock")
    protected Boolean isbnLock;

    @JsonProperty("linksLock")
    protected Boolean linksLock;

    @JsonProperty("tags")
    protected String[] tags;

    @JsonProperty("isbn")
    protected String isbn;

    @JsonProperty("links")
    protected WebLinkUpdateDto[] links;

    @JsonProperty("authors")
    protected AuthorUpdateDto[] authors;

    @JsonProperty("summary")
    protected String summary;

    @JsonProperty("releaseDate")
    protected java.time.Instant releaseDate;

    /**
     * Constructs a validated instance of {@link BookMetadataUpdateDto}.
     *
     * @param spec the specification to process
     */
    public BookMetadataUpdateDto(Consumer<BookMetadataUpdateDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link BookMetadataUpdateDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #BookMetadataUpdateDto(Consumer)} instead.
     * @param title title
     * @param titleLock titleLock
     * @param summaryLock summaryLock
     * @param number number
     * @param numberLock numberLock
     * @param numberSort numberSort
     * @param numberSortLock numberSortLock
     * @param releaseDateLock releaseDateLock
     * @param authorsLock authorsLock
     * @param tagsLock tagsLock
     * @param isbnLock isbnLock
     * @param linksLock linksLock
     * @param tags tags
     * @param isbn isbn
     * @param links links
     * @param authors authors
     * @param summary summary
     * @param releaseDate releaseDate
     */
    @ApiStatus.Internal
    public BookMetadataUpdateDto(String title, Boolean titleLock, Boolean summaryLock, String number, Boolean numberLock, Float numberSort, Boolean numberSortLock, Boolean releaseDateLock, Boolean authorsLock, Boolean tagsLock, Boolean isbnLock, Boolean linksLock, String[] tags, String isbn, WebLinkUpdateDto[] links, AuthorUpdateDto[] authors, String summary, Instant releaseDate) {
        this.title = title;
        this.titleLock = titleLock;
        this.summaryLock = summaryLock;
        this.number = number;
        this.numberLock = numberLock;
        this.numberSort = numberSort;
        this.numberSortLock = numberSortLock;
        this.releaseDateLock = releaseDateLock;
        this.authorsLock = authorsLock;
        this.tagsLock = tagsLock;
        this.isbnLock = isbnLock;
        this.linksLock = linksLock;
        this.tags = tags;
        this.isbn = isbn;
        this.links = links;
        this.authors = authors;
        this.summary = summary;
        this.releaseDate = releaseDate;
    }
}
