// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * BookImportBatchDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("BookImportBatchDto")
@JsonPropertyOrder({
    "books",
    "copyMode"
})
@Generated(value = "io.github.primelib.primecodegen")
public class BookImportBatchDto {

    @JsonProperty("books")
    protected BookImportDto[] books;

    @JsonProperty("copyMode")
    protected String copyMode;

    /**
     * Constructs a validated instance of {@link BookImportBatchDto}.
     *
     * @param spec the specification to process
     */
    public BookImportBatchDto(Consumer<BookImportBatchDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link BookImportBatchDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #BookImportBatchDto(Consumer)} instead.
     * @param books books
     * @param copyMode copyMode
     */
    @ApiStatus.Internal
    public BookImportBatchDto(BookImportDto[] books, String copyMode) {
        this.books = books;
        this.copyMode = copyMode;
    }
}
