// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * BookImportDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("BookImportDto")
@JsonPropertyOrder({
    "sourceFile",
    "seriesId",
    "upgradeBookId",
    "destinationName"
})
@Generated(value = "io.github.primelib.primecodegen")
public class BookImportDto {

    @JsonProperty("sourceFile")
    protected String sourceFile;

    @JsonProperty("seriesId")
    protected String seriesId;

    @JsonProperty("upgradeBookId")
    protected String upgradeBookId;

    @JsonProperty("destinationName")
    protected String destinationName;

    /**
     * Constructs a validated instance of {@link BookImportDto}.
     *
     * @param spec the specification to process
     */
    public BookImportDto(Consumer<BookImportDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link BookImportDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #BookImportDto(Consumer)} instead.
     * @param sourceFile sourceFile
     * @param seriesId seriesId
     * @param upgradeBookId upgradeBookId
     * @param destinationName destinationName
     */
    @ApiStatus.Internal
    public BookImportDto(String sourceFile, String seriesId, String upgradeBookId, String destinationName) {
        this.sourceFile = sourceFile;
        this.seriesId = seriesId;
        this.upgradeBookId = upgradeBookId;
        this.destinationName = destinationName;
    }
}
