// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.time.Instant;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * CollectionDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("CollectionDto")
@JsonPropertyOrder({
    "id",
    "name",
    "ordered",
    "seriesIds",
    "createdDate",
    "lastModifiedDate",
    "filtered"
})
@Generated(value = "io.github.primelib.primecodegen")
public class CollectionDto {

    @JsonProperty("id")
    protected String id;

    @JsonProperty("name")
    protected String name;

    @JsonProperty("ordered")
    protected Boolean ordered;

    @JsonProperty("seriesIds")
    protected String[] seriesIds;

    @JsonProperty("createdDate")
    protected java.time.Instant createdDate;

    @JsonProperty("lastModifiedDate")
    protected java.time.Instant lastModifiedDate;

    @JsonProperty("filtered")
    protected Boolean filtered;

    /**
     * Constructs a validated instance of {@link CollectionDto}.
     *
     * @param spec the specification to process
     */
    public CollectionDto(Consumer<CollectionDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link CollectionDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #CollectionDto(Consumer)} instead.
     * @param id id
     * @param name name
     * @param ordered ordered
     * @param seriesIds seriesIds
     * @param createdDate createdDate
     * @param lastModifiedDate lastModifiedDate
     * @param filtered filtered
     */
    @ApiStatus.Internal
    public CollectionDto(String id, String name, Boolean ordered, String[] seriesIds, Instant createdDate, Instant lastModifiedDate, Boolean filtered) {
        this.id = id;
        this.name = name;
        this.ordered = ordered;
        this.seriesIds = seriesIds;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;
        this.filtered = filtered;
    }
}
