// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * DirectoryListingDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("DirectoryListingDto")
@JsonPropertyOrder({
    "parent",
    "directories"
})
@Generated(value = "io.github.primelib.primecodegen")
public class DirectoryListingDto {

    @JsonProperty("parent")
    protected String parent;

    @JsonProperty("directories")
    protected PathDto[] directories;

    /**
     * Constructs a validated instance of {@link DirectoryListingDto}.
     *
     * @param spec the specification to process
     */
    public DirectoryListingDto(Consumer<DirectoryListingDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link DirectoryListingDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #DirectoryListingDto(Consumer)} instead.
     * @param parent parent
     * @param directories directories
     */
    @ApiStatus.Internal
    public DirectoryListingDto(String parent, PathDto[] directories) {
        this.parent = parent;
        this.directories = directories;
    }
}
