// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * FacetDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("FacetDto")
@JsonPropertyOrder({
    "metadata",
    "links"
})
@Generated(value = "io.github.primelib.primecodegen")
public class FacetDto {

    @JsonProperty("metadata")
    protected FeedMetadataDto metadata;

    @JsonProperty("links")
    protected WplinkDto[] links;

    /**
     * Constructs a validated instance of {@link FacetDto}.
     *
     * @param spec the specification to process
     */
    public FacetDto(Consumer<FacetDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link FacetDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #FacetDto(Consumer)} instead.
     * @param metadata metadata
     * @param links links
     */
    @ApiStatus.Internal
    public FacetDto(FeedMetadataDto metadata, WplinkDto[] links) {
        this.metadata = metadata;
        this.links = links;
    }
}
