// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.time.Instant;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * FeedMetadataDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("FeedMetadataDto")
@JsonPropertyOrder({
    "title",
    "subTitle",
    "type",
    "identifier",
    "modified",
    "description",
    "itemsPerPage",
    "currentPage",
    "numberOfItems"
})
@Generated(value = "io.github.primelib.primecodegen")
public class FeedMetadataDto {

    @JsonProperty("title")
    protected String title;

    @JsonProperty("subTitle")
    protected String subTitle;

    @JsonProperty("type")
    protected String type;

    @JsonProperty("identifier")
    protected String identifier;

    @JsonProperty("modified")
    protected java.time.Instant modified;

    @JsonProperty("description")
    protected String description;

    @JsonProperty("itemsPerPage")
    protected Integer itemsPerPage;

    @JsonProperty("currentPage")
    protected Integer currentPage;

    @JsonProperty("numberOfItems")
    protected Long numberOfItems;

    /**
     * Constructs a validated instance of {@link FeedMetadataDto}.
     *
     * @param spec the specification to process
     */
    public FeedMetadataDto(Consumer<FeedMetadataDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link FeedMetadataDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #FeedMetadataDto(Consumer)} instead.
     * @param title title
     * @param subTitle subTitle
     * @param type type
     * @param identifier identifier
     * @param modified modified
     * @param description description
     * @param itemsPerPage itemsPerPage
     * @param currentPage currentPage
     * @param numberOfItems numberOfItems
     */
    @ApiStatus.Internal
    public FeedMetadataDto(String title, String subTitle, String type, String identifier, Instant modified, String description, Integer itemsPerPage, Integer currentPage, Long numberOfItems) {
        this.title = title;
        this.subTitle = subTitle;
        this.type = type;
        this.identifier = identifier;
        this.modified = modified;
        this.description = description;
        this.itemsPerPage = itemsPerPage;
        this.currentPage = currentPage;
        this.numberOfItems = numberOfItems;
    }
}
