// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * FeedGroupDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("FeedGroupDto")
@JsonPropertyOrder({
    "metadata",
    "links",
    "navigation",
    "publications"
})
@Generated(value = "io.github.primelib.primecodegen")
public class FeedGroupDto {

    @JsonProperty("metadata")
    protected FeedMetadataDto metadata;

    @JsonProperty("links")
    protected WplinkDto[] links;

    @JsonProperty("navigation")
    protected WplinkDto[] navigation;

    @JsonProperty("publications")
    protected WppublicationDto[] publications;

    /**
     * Constructs a validated instance of {@link FeedGroupDto}.
     *
     * @param spec the specification to process
     */
    public FeedGroupDto(Consumer<FeedGroupDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link FeedGroupDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #FeedGroupDto(Consumer)} instead.
     * @param metadata metadata
     * @param links links
     * @param navigation navigation
     * @param publications publications
     */
    @ApiStatus.Internal
    public FeedGroupDto(FeedMetadataDto metadata, WplinkDto[] links, WplinkDto[] navigation, WppublicationDto[] publications) {
        this.metadata = metadata;
        this.links = links;
        this.navigation = navigation;
        this.publications = publications;
    }
}
