// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * JsonFeedDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("JsonFeedDto")
@JsonPropertyOrder({
    "version",
    "title",
    "homePageUrl",
    "description",
    "items"
})
@Generated(value = "io.github.primelib.primecodegen")
public class JsonFeedDto {

    @JsonProperty("version")
    protected String version;

    @JsonProperty("title")
    protected String title;

    @JsonProperty("home_page_url")
    protected String homePageUrl;

    @JsonProperty("description")
    protected String description;

    @JsonProperty("items")
    protected ItemDto[] items;

    /**
     * Constructs a validated instance of {@link JsonFeedDto}.
     *
     * @param spec the specification to process
     */
    public JsonFeedDto(Consumer<JsonFeedDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link JsonFeedDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #JsonFeedDto(Consumer)} instead.
     * @param version version
     * @param title title
     * @param homePageUrl homePageUrl
     * @param description description
     * @param items items
     */
    @ApiStatus.Internal
    public JsonFeedDto(String version, String title, String homePageUrl, String description, ItemDto[] items) {
        this.version = version;
        this.title = title;
        this.homePageUrl = homePageUrl;
        this.description = description;
        this.items = items;
    }
}
