// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * MediaDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("MediaDto")
@JsonPropertyOrder({
    "status",
    "mediaType",
    "pagesCount",
    "comment"
})
@Generated(value = "io.github.primelib.primecodegen")
public class MediaDto {

    @JsonProperty("status")
    protected String status;

    @JsonProperty("mediaType")
    protected String mediaType;

    @JsonProperty("pagesCount")
    protected Integer pagesCount;

    @JsonProperty("comment")
    protected String comment;

    /**
     * Constructs a validated instance of {@link MediaDto}.
     *
     * @param spec the specification to process
     */
    public MediaDto(Consumer<MediaDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link MediaDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #MediaDto(Consumer)} instead.
     * @param status status
     * @param mediaType mediaType
     * @param pagesCount pagesCount
     * @param comment comment
     */
    @ApiStatus.Internal
    public MediaDto(String status, String mediaType, Integer pagesCount, String comment) {
        this.status = status;
        this.mediaType = mediaType;
        this.pagesCount = pagesCount;
        this.comment = comment;
    }
}
