// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Oauth2ClientDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Oauth2ClientDto")
@JsonPropertyOrder({
    "name",
    "registrationId"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Oauth2ClientDto {

    @JsonProperty("name")
    protected String name;

    @JsonProperty("registrationId")
    protected String registrationId;

    /**
     * Constructs a validated instance of {@link Oauth2ClientDto}.
     *
     * @param spec the specification to process
     */
    public Oauth2ClientDto(Consumer<Oauth2ClientDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Oauth2ClientDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Oauth2ClientDto(Consumer)} instead.
     * @param name name
     * @param registrationId registrationId
     */
    @ApiStatus.Internal
    public Oauth2ClientDto(String name, String registrationId) {
        this.name = name;
        this.registrationId = registrationId;
    }
}
