// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * OpenSearchDescription
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("OpenSearchDescription")
@JsonPropertyOrder({
    "shortName",
    "description",
    "inputEncoding",
    "outputEncoding",
    "url"
})
@Generated(value = "io.github.primelib.primecodegen")
public class OpenSearchDescription {

    @JsonProperty("shortName")
    protected String shortName;

    @JsonProperty("description")
    protected String description;

    @JsonProperty("inputEncoding")
    protected String inputEncoding;

    @JsonProperty("outputEncoding")
    protected String outputEncoding;

    @JsonProperty("url")
    protected OpenSearchUrl url;

    /**
     * Constructs a validated instance of {@link OpenSearchDescription}.
     *
     * @param spec the specification to process
     */
    public OpenSearchDescription(Consumer<OpenSearchDescription> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link OpenSearchDescription}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #OpenSearchDescription(Consumer)} instead.
     * @param shortName shortName
     * @param description description
     * @param inputEncoding inputEncoding
     * @param outputEncoding outputEncoding
     * @param url url
     */
    @ApiStatus.Internal
    public OpenSearchDescription(String shortName, String description, String inputEncoding, String outputEncoding, OpenSearchUrl url) {
        this.shortName = shortName;
        this.description = description;
        this.inputEncoding = inputEncoding;
        this.outputEncoding = outputEncoding;
        this.url = url;
    }
}
