// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * PageDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("PageDto")
@JsonPropertyOrder({
    "number",
    "fileName",
    "mediaType",
    "width",
    "height",
    "sizeBytes",
    "size"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PageDto {

    @JsonProperty("number")
    protected Integer number;

    @JsonProperty("fileName")
    protected String fileName;

    @JsonProperty("mediaType")
    protected String mediaType;

    @JsonProperty("width")
    protected Integer width;

    @JsonProperty("height")
    protected Integer height;

    @JsonProperty("sizeBytes")
    protected Long sizeBytes;

    @JsonProperty("size")
    protected String size;

    /**
     * Constructs a validated instance of {@link PageDto}.
     *
     * @param spec the specification to process
     */
    public PageDto(Consumer<PageDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link PageDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PageDto(Consumer)} instead.
     * @param number number
     * @param fileName fileName
     * @param mediaType mediaType
     * @param width width
     * @param height height
     * @param sizeBytes sizeBytes
     * @param size size
     */
    @ApiStatus.Internal
    public PageDto(Integer number, String fileName, String mediaType, Integer width, Integer height, Long sizeBytes, String size) {
        this.number = number;
        this.fileName = fileName;
        this.mediaType = mediaType;
        this.width = width;
        this.height = height;
        this.sizeBytes = sizeBytes;
        this.size = size;
    }
}
