// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * PageableObject
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("PageableObject")
@JsonPropertyOrder({
    "pageNumber",
    "pageSize",
    "paged",
    "unpaged",
    "offset",
    "sort"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PageableObject {

    @JsonProperty("pageNumber")
    protected Integer pageNumber;

    @JsonProperty("pageSize")
    protected Integer pageSize;

    @JsonProperty("paged")
    protected Boolean paged;

    @JsonProperty("unpaged")
    protected Boolean unpaged;

    @JsonProperty("offset")
    protected Long offset;

    @JsonProperty("sort")
    protected SortObject sort;

    /**
     * Constructs a validated instance of {@link PageableObject}.
     *
     * @param spec the specification to process
     */
    public PageableObject(Consumer<PageableObject> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link PageableObject}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PageableObject(Consumer)} instead.
     * @param pageNumber pageNumber
     * @param pageSize pageSize
     * @param paged paged
     * @param unpaged unpaged
     * @param offset offset
     * @param sort sort
     */
    @ApiStatus.Internal
    public PageableObject(Integer pageNumber, Integer pageSize, Boolean paged, Boolean unpaged, Long offset, SortObject sort) {
        this.pageNumber = pageNumber;
        this.pageSize = pageSize;
        this.paged = paged;
        this.unpaged = unpaged;
        this.offset = offset;
        this.sort = sort;
    }
}
