// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.time.Instant;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * PageHashKnownDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("PageHashKnownDto")
@JsonPropertyOrder({
    "hash",
    "size",
    "action",
    "deleteCount",
    "matchCount",
    "created",
    "lastModified"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PageHashKnownDto {

    @JsonProperty("hash")
    protected String hash;

    @JsonProperty("size")
    protected Long size;

    @JsonProperty("action")
    protected String action;

    @JsonProperty("deleteCount")
    protected Integer deleteCount;

    @JsonProperty("matchCount")
    protected Integer matchCount;

    @JsonProperty("created")
    protected java.time.Instant created;

    @JsonProperty("lastModified")
    protected java.time.Instant lastModified;

    /**
     * Constructs a validated instance of {@link PageHashKnownDto}.
     *
     * @param spec the specification to process
     */
    public PageHashKnownDto(Consumer<PageHashKnownDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link PageHashKnownDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PageHashKnownDto(Consumer)} instead.
     * @param hash hash
     * @param size size
     * @param action action
     * @param deleteCount deleteCount
     * @param matchCount matchCount
     * @param created created
     * @param lastModified lastModified
     */
    @ApiStatus.Internal
    public PageHashKnownDto(String hash, Long size, String action, Integer deleteCount, Integer matchCount, Instant created, Instant lastModified) {
        this.hash = hash;
        this.size = size;
        this.action = action;
        this.deleteCount = deleteCount;
        this.matchCount = matchCount;
        this.created = created;
        this.lastModified = lastModified;
    }
}
