// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * PageHashUnknownDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("PageHashUnknownDto")
@JsonPropertyOrder({
    "hash",
    "size",
    "matchCount"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PageHashUnknownDto {

    @JsonProperty("hash")
    protected String hash;

    @JsonProperty("size")
    protected Long size;

    @JsonProperty("matchCount")
    protected Integer matchCount;

    /**
     * Constructs a validated instance of {@link PageHashUnknownDto}.
     *
     * @param spec the specification to process
     */
    public PageHashUnknownDto(Consumer<PageHashUnknownDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link PageHashUnknownDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PageHashUnknownDto(Consumer)} instead.
     * @param hash hash
     * @param size size
     * @param matchCount matchCount
     */
    @ApiStatus.Internal
    public PageHashUnknownDto(String hash, Long size, Integer matchCount) {
        this.hash = hash;
        this.size = size;
        this.matchCount = matchCount;
    }
}
