// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * PathDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("PathDto")
@JsonPropertyOrder({
    "type",
    "name",
    "path"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PathDto {

    @JsonProperty("type")
    protected String type;

    @JsonProperty("name")
    protected String name;

    @JsonProperty("path")
    protected String path;

    /**
     * Constructs a validated instance of {@link PathDto}.
     *
     * @param spec the specification to process
     */
    public PathDto(Consumer<PathDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link PathDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PathDto(Consumer)} instead.
     * @param type type
     * @param name name
     * @param path path
     */
    @ApiStatus.Internal
    public PathDto(String type, String name, String path) {
        this.type = type;
        this.name = name;
        this.path = path;
    }
}
