// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ReadListMatchDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ReadListMatchDto")
@JsonPropertyOrder({
    "name",
    "errorCode"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ReadListMatchDto {

    @JsonProperty("name")
    protected String name;

    @JsonProperty("errorCode")
    protected String errorCode;

    /**
     * Constructs a validated instance of {@link ReadListMatchDto}.
     *
     * @param spec the specification to process
     */
    public ReadListMatchDto(Consumer<ReadListMatchDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ReadListMatchDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ReadListMatchDto(Consumer)} instead.
     * @param name name
     * @param errorCode errorCode
     */
    @ApiStatus.Internal
    public ReadListMatchDto(String name, String errorCode) {
        this.name = name;
        this.errorCode = errorCode;
    }
}
