// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ReadListRequestBookMatchesDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ReadListRequestBookMatchesDto")
@JsonPropertyOrder({
    "request",
    "matches"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ReadListRequestBookMatchesDto {

    @JsonProperty("request")
    protected ReadListRequestBookDto request;

    @JsonProperty("matches")
    protected ReadListRequestBookMatchDto[] matches;

    /**
     * Constructs a validated instance of {@link ReadListRequestBookMatchesDto}.
     *
     * @param spec the specification to process
     */
    public ReadListRequestBookMatchesDto(Consumer<ReadListRequestBookMatchesDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ReadListRequestBookMatchesDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ReadListRequestBookMatchesDto(Consumer)} instead.
     * @param request request
     * @param matches matches
     */
    @ApiStatus.Internal
    public ReadListRequestBookMatchesDto(ReadListRequestBookDto request, ReadListRequestBookMatchDto[] matches) {
        this.request = request;
        this.matches = matches;
    }
}
