// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ReadListRequestBookDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ReadListRequestBookDto")
@JsonPropertyOrder({
    "series",
    "number"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ReadListRequestBookDto {

    @JsonProperty("series")
    protected String[] series;

    @JsonProperty("number")
    protected String number;

    /**
     * Constructs a validated instance of {@link ReadListRequestBookDto}.
     *
     * @param spec the specification to process
     */
    public ReadListRequestBookDto(Consumer<ReadListRequestBookDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ReadListRequestBookDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ReadListRequestBookDto(Consumer)} instead.
     * @param series series
     * @param number number
     */
    @ApiStatus.Internal
    public ReadListRequestBookDto(String[] series, String number) {
        this.series = series;
        this.number = number;
    }
}
