// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ReadListRequestBookMatchBookDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ReadListRequestBookMatchBookDto")
@JsonPropertyOrder({
    "bookId",
    "number",
    "title"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ReadListRequestBookMatchBookDto {

    @JsonProperty("bookId")
    protected String bookId;

    @JsonProperty("number")
    protected String number;

    @JsonProperty("title")
    protected String title;

    /**
     * Constructs a validated instance of {@link ReadListRequestBookMatchBookDto}.
     *
     * @param spec the specification to process
     */
    public ReadListRequestBookMatchBookDto(Consumer<ReadListRequestBookMatchBookDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ReadListRequestBookMatchBookDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ReadListRequestBookMatchBookDto(Consumer)} instead.
     * @param bookId bookId
     * @param number number
     * @param title title
     */
    @ApiStatus.Internal
    public ReadListRequestBookMatchBookDto(String bookId, String number, String title) {
        this.bookId = bookId;
        this.number = number;
        this.title = title;
    }
}
