// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.time.Instant;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ReadListRequestBookMatchSeriesDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ReadListRequestBookMatchSeriesDto")
@JsonPropertyOrder({
    "seriesId",
    "title",
    "releaseDate"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ReadListRequestBookMatchSeriesDto {

    @JsonProperty("seriesId")
    protected String seriesId;

    @JsonProperty("title")
    protected String title;

    @JsonProperty("releaseDate")
    protected java.time.Instant releaseDate;

    /**
     * Constructs a validated instance of {@link ReadListRequestBookMatchSeriesDto}.
     *
     * @param spec the specification to process
     */
    public ReadListRequestBookMatchSeriesDto(Consumer<ReadListRequestBookMatchSeriesDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ReadListRequestBookMatchSeriesDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ReadListRequestBookMatchSeriesDto(Consumer)} instead.
     * @param seriesId seriesId
     * @param title title
     * @param releaseDate releaseDate
     */
    @ApiStatus.Internal
    public ReadListRequestBookMatchSeriesDto(String seriesId, String title, Instant releaseDate) {
        this.seriesId = seriesId;
        this.title = title;
        this.releaseDate = releaseDate;
    }
}
