// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ScanRequestDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ScanRequestDto")
@JsonPropertyOrder({
    "path"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ScanRequestDto {

    @JsonProperty("path")
    protected String path;

    /**
     * Constructs a validated instance of {@link ScanRequestDto}.
     *
     * @param spec the specification to process
     */
    public ScanRequestDto(Consumer<ScanRequestDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ScanRequestDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ScanRequestDto(Consumer)} instead.
     * @param path path
     */
    @ApiStatus.Internal
    public ScanRequestDto(String path) {
        this.path = path;
    }
}
