// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.time.Instant;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * SeriesDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("SeriesDto")
@JsonPropertyOrder({
    "id",
    "libraryId",
    "name",
    "url",
    "created",
    "lastModified",
    "fileLastModified",
    "booksCount",
    "booksReadCount",
    "booksUnreadCount",
    "booksInProgressCount",
    "metadata",
    "booksMetadata",
    "deleted",
    "oneshot"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SeriesDto {

    @JsonProperty("id")
    protected String id;

    @JsonProperty("libraryId")
    protected String libraryId;

    @JsonProperty("name")
    protected String name;

    @JsonProperty("url")
    protected String url;

    @JsonProperty("created")
    protected java.time.Instant created;

    @JsonProperty("lastModified")
    protected java.time.Instant lastModified;

    @JsonProperty("fileLastModified")
    protected java.time.Instant fileLastModified;

    @JsonProperty("booksCount")
    protected Integer booksCount;

    @JsonProperty("booksReadCount")
    protected Integer booksReadCount;

    @JsonProperty("booksUnreadCount")
    protected Integer booksUnreadCount;

    @JsonProperty("booksInProgressCount")
    protected Integer booksInProgressCount;

    @JsonProperty("metadata")
    protected SeriesMetadataDto metadata;

    @JsonProperty("booksMetadata")
    protected BookMetadataAggregationDto booksMetadata;

    @JsonProperty("deleted")
    protected Boolean deleted;

    @JsonProperty("oneshot")
    protected Boolean oneshot;

    /**
     * Constructs a validated instance of {@link SeriesDto}.
     *
     * @param spec the specification to process
     */
    public SeriesDto(Consumer<SeriesDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link SeriesDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SeriesDto(Consumer)} instead.
     * @param id id
     * @param libraryId libraryId
     * @param name name
     * @param url url
     * @param created created
     * @param lastModified lastModified
     * @param fileLastModified fileLastModified
     * @param booksCount booksCount
     * @param booksReadCount booksReadCount
     * @param booksUnreadCount booksUnreadCount
     * @param booksInProgressCount booksInProgressCount
     * @param metadata metadata
     * @param booksMetadata booksMetadata
     * @param deleted deleted
     * @param oneshot oneshot
     */
    @ApiStatus.Internal
    public SeriesDto(String id, String libraryId, String name, String url, Instant created, Instant lastModified, Instant fileLastModified, Integer booksCount, Integer booksReadCount, Integer booksUnreadCount, Integer booksInProgressCount, SeriesMetadataDto metadata, BookMetadataAggregationDto booksMetadata, Boolean deleted, Boolean oneshot) {
        this.id = id;
        this.libraryId = libraryId;
        this.name = name;
        this.url = url;
        this.created = created;
        this.lastModified = lastModified;
        this.fileLastModified = fileLastModified;
        this.booksCount = booksCount;
        this.booksReadCount = booksReadCount;
        this.booksUnreadCount = booksUnreadCount;
        this.booksInProgressCount = booksInProgressCount;
        this.metadata = metadata;
        this.booksMetadata = booksMetadata;
        this.deleted = deleted;
        this.oneshot = oneshot;
    }
}
