// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * TachiyomiReadProgressDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("TachiyomiReadProgressDto")
@JsonPropertyOrder({
    "booksCount",
    "booksReadCount",
    "booksUnreadCount",
    "booksInProgressCount",
    "lastReadContinuousIndex"
})
@Generated(value = "io.github.primelib.primecodegen")
public class TachiyomiReadProgressDto {

    @JsonProperty("booksCount")
    protected Integer booksCount;

    @JsonProperty("booksReadCount")
    protected Integer booksReadCount;

    @JsonProperty("booksUnreadCount")
    protected Integer booksUnreadCount;

    @JsonProperty("booksInProgressCount")
    protected Integer booksInProgressCount;

    @JsonProperty("lastReadContinuousIndex")
    protected Integer lastReadContinuousIndex;

    /**
     * Constructs a validated instance of {@link TachiyomiReadProgressDto}.
     *
     * @param spec the specification to process
     */
    public TachiyomiReadProgressDto(Consumer<TachiyomiReadProgressDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link TachiyomiReadProgressDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #TachiyomiReadProgressDto(Consumer)} instead.
     * @param booksCount booksCount
     * @param booksReadCount booksReadCount
     * @param booksUnreadCount booksUnreadCount
     * @param booksInProgressCount booksInProgressCount
     * @param lastReadContinuousIndex lastReadContinuousIndex
     */
    @ApiStatus.Internal
    public TachiyomiReadProgressDto(Integer booksCount, Integer booksReadCount, Integer booksUnreadCount, Integer booksInProgressCount, Integer lastReadContinuousIndex) {
        this.booksCount = booksCount;
        this.booksReadCount = booksReadCount;
        this.booksUnreadCount = booksUnreadCount;
        this.booksInProgressCount = booksInProgressCount;
        this.lastReadContinuousIndex = lastReadContinuousIndex;
    }
}
