// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * TachiyomiReadProgressV2Dto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("TachiyomiReadProgressV2Dto")
@JsonPropertyOrder({
    "booksCount",
    "booksReadCount",
    "booksUnreadCount",
    "booksInProgressCount",
    "lastReadContinuousNumberSort",
    "maxNumberSort"
})
@Generated(value = "io.github.primelib.primecodegen")
public class TachiyomiReadProgressV2Dto {

    @JsonProperty("booksCount")
    protected Integer booksCount;

    @JsonProperty("booksReadCount")
    protected Integer booksReadCount;

    @JsonProperty("booksUnreadCount")
    protected Integer booksUnreadCount;

    @JsonProperty("booksInProgressCount")
    protected Integer booksInProgressCount;

    @JsonProperty("lastReadContinuousNumberSort")
    protected Float lastReadContinuousNumberSort;

    @JsonProperty("maxNumberSort")
    protected Float maxNumberSort;

    /**
     * Constructs a validated instance of {@link TachiyomiReadProgressV2Dto}.
     *
     * @param spec the specification to process
     */
    public TachiyomiReadProgressV2Dto(Consumer<TachiyomiReadProgressV2Dto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link TachiyomiReadProgressV2Dto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #TachiyomiReadProgressV2Dto(Consumer)} instead.
     * @param booksCount booksCount
     * @param booksReadCount booksReadCount
     * @param booksUnreadCount booksUnreadCount
     * @param booksInProgressCount booksInProgressCount
     * @param lastReadContinuousNumberSort lastReadContinuousNumberSort
     * @param maxNumberSort maxNumberSort
     */
    @ApiStatus.Internal
    public TachiyomiReadProgressV2Dto(Integer booksCount, Integer booksReadCount, Integer booksUnreadCount, Integer booksInProgressCount, Float lastReadContinuousNumberSort, Float maxNumberSort) {
        this.booksCount = booksCount;
        this.booksReadCount = booksReadCount;
        this.booksUnreadCount = booksUnreadCount;
        this.booksInProgressCount = booksInProgressCount;
        this.lastReadContinuousNumberSort = lastReadContinuousNumberSort;
        this.maxNumberSort = maxNumberSort;
    }
}
