// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ThumbnailSeriesDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ThumbnailSeriesDto")
@JsonPropertyOrder({
    "id",
    "seriesId",
    "type",
    "selected",
    "mediaType",
    "fileSize",
    "width",
    "height"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ThumbnailSeriesDto {

    @JsonProperty("id")
    protected String id;

    @JsonProperty("seriesId")
    protected String seriesId;

    @JsonProperty("type")
    protected String type;

    @JsonProperty("selected")
    protected Boolean selected;

    @JsonProperty("mediaType")
    protected String mediaType;

    @JsonProperty("fileSize")
    protected Long fileSize;

    @JsonProperty("width")
    protected Integer width;

    @JsonProperty("height")
    protected Integer height;

    /**
     * Constructs a validated instance of {@link ThumbnailSeriesDto}.
     *
     * @param spec the specification to process
     */
    public ThumbnailSeriesDto(Consumer<ThumbnailSeriesDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ThumbnailSeriesDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ThumbnailSeriesDto(Consumer)} instead.
     * @param id id
     * @param seriesId seriesId
     * @param type type
     * @param selected selected
     * @param mediaType mediaType
     * @param fileSize fileSize
     * @param width width
     * @param height height
     */
    @ApiStatus.Internal
    public ThumbnailSeriesDto(String id, String seriesId, String type, Boolean selected, String mediaType, Long fileSize, Integer width, Integer height) {
        this.id = id;
        this.seriesId = seriesId;
        this.type = type;
        this.selected = selected;
        this.mediaType = mediaType;
        this.fileSize = fileSize;
        this.width = width;
        this.height = height;
    }
}
