// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * UserDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("UserDto")
@JsonPropertyOrder({
    "id",
    "email",
    "roles",
    "sharedAllLibraries",
    "sharedLibrariesIds",
    "labelsAllow",
    "labelsExclude",
    "ageRestriction"
})
@Generated(value = "io.github.primelib.primecodegen")
public class UserDto {

    @JsonProperty("id")
    protected String id;

    @JsonProperty("email")
    protected String email;

    @JsonProperty("roles")
    protected String[] roles;

    @JsonProperty("sharedAllLibraries")
    protected Boolean sharedAllLibraries;

    @JsonProperty("sharedLibrariesIds")
    protected String[] sharedLibrariesIds;

    @JsonProperty("labelsAllow")
    protected String[] labelsAllow;

    @JsonProperty("labelsExclude")
    protected String[] labelsExclude;

    @JsonProperty("ageRestriction")
    protected AgeRestrictionDto ageRestriction;

    /**
     * Constructs a validated instance of {@link UserDto}.
     *
     * @param spec the specification to process
     */
    public UserDto(Consumer<UserDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link UserDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #UserDto(Consumer)} instead.
     * @param id id
     * @param email email
     * @param roles roles
     * @param sharedAllLibraries sharedAllLibraries
     * @param sharedLibrariesIds sharedLibrariesIds
     * @param labelsAllow labelsAllow
     * @param labelsExclude labelsExclude
     * @param ageRestriction ageRestriction
     */
    @ApiStatus.Internal
    public UserDto(String id, String email, String[] roles, Boolean sharedAllLibraries, String[] sharedLibrariesIds, String[] labelsAllow, String[] labelsExclude, AgeRestrictionDto ageRestriction) {
        this.id = id;
        this.email = email;
        this.roles = roles;
        this.sharedAllLibraries = sharedAllLibraries;
        this.sharedLibrariesIds = sharedLibrariesIds;
        this.labelsAllow = labelsAllow;
        this.labelsExclude = labelsExclude;
        this.ageRestriction = ageRestriction;
    }
}
