// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * UserUpdateDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("UserUpdateDto")
@JsonPropertyOrder({
    "roles",
    "labelsAllow",
    "labelsExclude",
    "ageRestriction",
    "sharedLibraries"
})
@Generated(value = "io.github.primelib.primecodegen")
public class UserUpdateDto {

    @JsonProperty("roles")
    protected String[] roles;

    @JsonProperty("labelsAllow")
    protected String[] labelsAllow;

    @JsonProperty("labelsExclude")
    protected String[] labelsExclude;

    @JsonProperty("ageRestriction")
    protected AgeRestrictionUpdateDto ageRestriction;

    @JsonProperty("sharedLibraries")
    protected SharedLibrariesUpdateDto sharedLibraries;

    /**
     * Constructs a validated instance of {@link UserUpdateDto}.
     *
     * @param spec the specification to process
     */
    public UserUpdateDto(Consumer<UserUpdateDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link UserUpdateDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #UserUpdateDto(Consumer)} instead.
     * @param roles roles
     * @param labelsAllow labelsAllow
     * @param labelsExclude labelsExclude
     * @param ageRestriction ageRestriction
     * @param sharedLibraries sharedLibraries
     */
    @ApiStatus.Internal
    public UserUpdateDto(String[] roles, String[] labelsAllow, String[] labelsExclude, AgeRestrictionUpdateDto ageRestriction, SharedLibrariesUpdateDto sharedLibraries) {
        this.roles = roles;
        this.labelsAllow = labelsAllow;
        this.labelsExclude = labelsExclude;
        this.ageRestriction = ageRestriction;
        this.sharedLibraries = sharedLibraries;
    }
}
