// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Violation
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Violation")
@JsonPropertyOrder({
    "fieldName",
    "message"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Violation {

    @JsonProperty("fieldName")
    protected String fieldName;

    @JsonProperty("message")
    protected String message;

    /**
     * Constructs a validated instance of {@link Violation}.
     *
     * @param spec the specification to process
     */
    public Violation(Consumer<Violation> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Violation}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Violation(Consumer)} instead.
     * @param fieldName fieldName
     * @param message message
     */
    @ApiStatus.Internal
    public Violation(String fieldName, String message) {
        this.fieldName = fieldName;
        this.message = message;
    }
}
