// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * WppublicationDto
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("WppublicationDto")
@JsonPropertyOrder({
    "context",
    "metadata",
    "links",
    "images",
    "readingOrder",
    "resources",
    "toc"
})
@Generated(value = "io.github.primelib.primecodegen")
public class WppublicationDto {

    @JsonProperty("context")
    protected String context;

    @JsonProperty("metadata")
    protected WpmetadataDto metadata;

    @JsonProperty("links")
    protected WplinkDto[] links;

    @JsonProperty("images")
    protected WplinkDto[] images;

    @JsonProperty("readingOrder")
    protected WplinkDto[] readingOrder;

    @JsonProperty("resources")
    protected WplinkDto[] resources;

    @JsonProperty("toc")
    protected WplinkDto[] toc;

    /**
     * Constructs a validated instance of {@link WppublicationDto}.
     *
     * @param spec the specification to process
     */
    public WppublicationDto(Consumer<WppublicationDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link WppublicationDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #WppublicationDto(Consumer)} instead.
     * @param context context
     * @param metadata metadata
     * @param links links
     * @param images images
     * @param readingOrder readingOrder
     * @param resources resources
     * @param toc toc
     */
    @ApiStatus.Internal
    public WppublicationDto(String context, WpmetadataDto metadata, WplinkDto[] links, WplinkDto[] images, WplinkDto[] readingOrder, WplinkDto[] resources, WplinkDto[] toc) {
        this.context = context;
        this.metadata = metadata;
        this.links = links;
        this.images = images;
        this.readingOrder = readingOrder;
        this.resources = resources;
        this.toc = toc;
    }
}
