// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * ActionEnum
 *
 */
@JsonTypeName("ActionEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum ActionEnum {
    DELETE_AUTO("DELETE_AUTO"),
    DELETE_MANUAL("DELETE_MANUAL"),
    IGNORE("IGNORE"),
    ;

    private final String value;

    ActionEnum(String value) {
        this.value = value;
    }
}
