// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * CopyModeEnum
 *
 */
@JsonTypeName("CopyModeEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum CopyModeEnum {
    COPY("COPY"),
    HARDLINK("HARDLINK"),
    MOVE("MOVE"),
    ;

    private final String value;

    CopyModeEnum(String value) {
        this.value = value;
    }
}
