// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * ReadingDirectionEnum
 *
 */
@JsonTypeName("ReadingDirectionEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum ReadingDirectionEnum {
    LEFT_TO_RIGHT("LEFT_TO_RIGHT"),
    RIGHT_TO_LEFT("RIGHT_TO_LEFT"),
    VERTICAL("VERTICAL"),
    WEBTOON("WEBTOON"),
    ;

    private final String value;

    ReadingDirectionEnum(String value) {
        this.value = value;
    }
}
