// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * SeriesCoverEnum
 *
 */
@JsonTypeName("SeriesCoverEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum SeriesCoverEnum {
    FIRST("FIRST"),
    FIRST_UNREAD_OR_FIRST("FIRST_UNREAD_OR_FIRST"),
    FIRST_UNREAD_OR_LAST("FIRST_UNREAD_OR_LAST"),
    LAST("LAST"),
    ;

    private final String value;

    SeriesCoverEnum(String value) {
        this.value = value;
    }
}
