// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * ThumbnailSizeEnum
 *
 */
@JsonTypeName("ThumbnailSizeEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum ThumbnailSizeEnum {
    DEFAULT("DEFAULT"),
    LARGE("LARGE"),
    MEDIUM("MEDIUM"),
    XLARGE("XLARGE"),
    ;

    private final String value;

    ThumbnailSizeEnum(String value) {
        this.value = value;
    }
}
