// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type DeleteCollectionByIDV1Request struct {
	Id *string `pathParam:"style=simple,explode=false,name=id"`
}

type DeleteCollectionByIDV1Response struct {
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// DeleteCollectionByIDV1
//
//meta:operation DELETE /api/v1/collections/{id}
func DeleteCollectionByIDV1(client *resty.Client, ctx context.Context, req DeleteCollectionByIDV1Request) (*DeleteCollectionByIDV1Response, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}

	// send the request
	resp, err := r.Delete("/api/v1/collections/{id}")
	if err != nil {
		return nil, err
	}

	return &DeleteCollectionByIDV1Response{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
	}, nil
}
