// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type DeleteUserByIDV2Request struct {
	Id *string `pathParam:"style=simple,explode=false,name=id"`
}

type DeleteUserByIDV2Response struct {
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// DeleteUserByIDV2
//
//meta:operation DELETE /api/v2/users/{id}
func DeleteUserByIDV2(client *resty.Client, ctx context.Context, req DeleteUserByIDV2Request) (*DeleteUserByIDV2Response, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}

	// send the request
	resp, err := r.Delete("/api/v2/users/{id}")
	if err != nil {
		return nil, err
	}

	return &DeleteUserByIDV2Response{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
	}, nil
}
