// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type GetAuthorsRolesV1Request struct {
}

type GetAuthorsRolesV1Response struct {
	// Success response
	Result []*string
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetAuthorsRolesV1
//
//meta:operation GET /api/v1/authors/roles
func GetAuthorsRolesV1(client *resty.Client, ctx context.Context, req GetAuthorsRolesV1Request) (*GetAuthorsRolesV1Response, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	var result []*string
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/api/v1/authors/roles")
	if err != nil {
		return nil, err
	}

	return &GetAuthorsRolesV1Response{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
	}, nil
}
