// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/komga-client/sdk/go/pkgs/models"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type GetAuthorsV2Request struct {
	Search       *string `queryParam:"style=simple,explode=false,name=search"`
	Role         *string `queryParam:"style=simple,explode=false,name=role"`
	LibraryId    *string `queryParam:"style=simple,explode=false,name=library_id"`
	CollectionId *string `queryParam:"style=simple,explode=false,name=collection_id"`
	SeriesId     *string `queryParam:"style=simple,explode=false,name=series_id"`
	ReadlistId   *string `queryParam:"style=simple,explode=false,name=readlist_id"`
	Unpaged      *bool   `queryParam:"style=simple,explode=false,name=unpaged"`
	Page         *int64  `queryParam:"style=simple,explode=false,name=page"` // Zero-based page index (0..N)
	Size         *int64  `queryParam:"style=simple,explode=false,name=size"` // The size of the page to be returned
}

type GetAuthorsV2Response struct {
	// Success response
	Result *models.PageAuthorDto
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetAuthorsV2
//
//meta:operation GET /api/v2/authors
func GetAuthorsV2(client *resty.Client, ctx context.Context, req GetAuthorsV2Request) (*GetAuthorsV2Response, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.PageAuthorDto)
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/api/v2/authors")
	if err != nil {
		return nil, err
	}

	return &GetAuthorsV2Response{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
