// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/komga-client/sdk/go/pkgs/models"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type GetOpdsV12SearchV1Request struct {
}

type GetOpdsV12SearchV1Response struct {
	// Success response
	Result *models.OpenSearchDescription
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetOpdsV12SearchV1
//
//meta:operation GET /opds/v1.2/search
func GetOpdsV12SearchV1(client *resty.Client, ctx context.Context, req GetOpdsV12SearchV1Request) (*GetOpdsV12SearchV1Response, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.OpenSearchDescription)
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/opds/v1.2/search")
	if err != nil {
		return nil, err
	}

	return &GetOpdsV12SearchV1Response{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
