// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/komga-client/sdk/go/pkgs/models"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type GetReadlistByIDThumbnailsV1Request struct {
	Id *string `pathParam:"style=simple,explode=false,name=id"`
}

type GetReadlistByIDThumbnailsV1Response struct {
	// Success response
	Result []*models.ThumbnailReadListDto
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetReadlistByIDThumbnailsV1
//
//meta:operation GET /api/v1/readlists/{id}/thumbnails
func GetReadlistByIDThumbnailsV1(client *resty.Client, ctx context.Context, req GetReadlistByIDThumbnailsV1Request) (*GetReadlistByIDThumbnailsV1Response, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	var result []*models.ThumbnailReadListDto
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/api/v1/readlists/{id}/thumbnails")
	if err != nil {
		return nil, err
	}

	return &GetReadlistByIDThumbnailsV1Response{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
	}, nil
}
