// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/komga-client/sdk/go/pkgs/models"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type GetReadlistByIDBookByBookIDNextV1Request struct {
	Id     *string `pathParam:"style=simple,explode=false,name=id"`
	BookId *string `pathParam:"style=simple,explode=false,name=bookId"`
}

type GetReadlistByIDBookByBookIDNextV1Response struct {
	// Success response
	Result *models.BookDto
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetReadlistByIDBookByBookIDNextV1
//
//meta:operation GET /api/v1/readlists/{id}/books/{bookId}/next
func GetReadlistByIDBookByBookIDNextV1(client *resty.Client, ctx context.Context, req GetReadlistByIDBookByBookIDNextV1Request) (*GetReadlistByIDBookByBookIDNextV1Response, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.BookDto)
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/api/v1/readlists/{id}/books/{bookId}/next")
	if err != nil {
		return nil, err
	}

	return &GetReadlistByIDBookByBookIDNextV1Response{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
