// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/komga-client/sdk/go/pkgs/models"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type PatchBookByBookIDReadProgressV1Request struct {
	BookId  *string                       `pathParam:"style=simple,explode=false,name=bookId"`
	Payload *models.ReadProgressUpdateDto `bodyParam:""`
}

type PatchBookByBookIDReadProgressV1Response struct {
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// PatchBookByBookIDReadProgressV1 Mark book as read and/or change page progress
//
//meta:operation PATCH /api/v1/books/{bookId}/read-progress
func PatchBookByBookIDReadProgressV1(client *resty.Client, ctx context.Context, req PatchBookByBookIDReadProgressV1Request) (*PatchBookByBookIDReadProgressV1Response, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}

	// send the request
	resp, err := r.Patch("/api/v1/books/{bookId}/read-progress")
	if err != nil {
		return nil, err
	}

	return &PatchBookByBookIDReadProgressV1Response{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
	}, nil
}
