// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/komga-client/sdk/go/pkgs/models"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type PatchUserByIDV2Request struct {
	Id      *string               `pathParam:"style=simple,explode=false,name=id"`
	Payload *models.UserUpdateDto `bodyParam:""`
}

type PatchUserByIDV2Response struct {
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// PatchUserByIDV2
//
//meta:operation PATCH /api/v2/users/{id}
func PatchUserByIDV2(client *resty.Client, ctx context.Context, req PatchUserByIDV2Request) (*PatchUserByIDV2Response, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}

	// send the request
	resp, err := r.Patch("/api/v2/users/{id}")
	if err != nil {
		return nil, err
	}

	return &PatchUserByIDV2Response{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
	}, nil
}
