// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/komga-client/sdk/go/pkgs/models"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type PostPageHashByPageHashDeleteMatchV1Request struct {
	PageHash *string                  `pathParam:"style=simple,explode=false,name=pageHash"`
	Payload  *models.PageHashMatchDto `bodyParam:""`
}

type PostPageHashByPageHashDeleteMatchV1Response struct {
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// PostPageHashByPageHashDeleteMatchV1
//
//meta:operation POST /api/v1/page-hashes/{pageHash}/delete-match
func PostPageHashByPageHashDeleteMatchV1(client *resty.Client, ctx context.Context, req PostPageHashByPageHashDeleteMatchV1Request) (*PostPageHashByPageHashDeleteMatchV1Response, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}

	// send the request
	resp, err := r.Post("/api/v1/page-hashes/{pageHash}/delete-match")
	if err != nil {
		return nil, err
	}

	return &PostPageHashByPageHashDeleteMatchV1Response{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
	}, nil
}
