// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/komga-client/sdk/go/pkgs/models"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type PostReadlistsV1Request struct {
	Payload *models.ReadListCreationDto `bodyParam:""`
}

type PostReadlistsV1Response struct {
	// Success response
	Result *models.ReadListDto
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// PostReadlistsV1
//
//meta:operation POST /api/v1/readlists
func PostReadlistsV1(client *resty.Client, ctx context.Context, req PostReadlistsV1Request) (*PostReadlistsV1Response, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.ReadListDto)
	r.SetResult(result)

	// send the request
	resp, err := r.Post("/api/v1/readlists")
	if err != nil {
		return nil, err
	}

	return &PostReadlistsV1Response{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
