// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/komga-client/sdk/go/pkgs/models"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type PutSeriesBySeriesIDReadProgressTachiyomiV2Request struct {
	SeriesId *string                                  `pathParam:"style=simple,explode=false,name=seriesId"`
	Payload  *models.TachiyomiReadProgressUpdateV2Dto `bodyParam:""`
}

type PutSeriesBySeriesIDReadProgressTachiyomiV2Response struct {
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// PutSeriesBySeriesIDReadProgressTachiyomiV2
//
//meta:operation PUT /api/v2/series/{seriesId}/read-progress/tachiyomi
func PutSeriesBySeriesIDReadProgressTachiyomiV2(client *resty.Client, ctx context.Context, req PutSeriesBySeriesIDReadProgressTachiyomiV2Request) (*PutSeriesBySeriesIDReadProgressTachiyomiV2Response, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}

	// send the request
	resp, err := r.Put("/api/v2/series/{seriesId}/read-progress/tachiyomi")
	if err != nil {
		return nil, err
	}

	return &PutSeriesBySeriesIDReadProgressTachiyomiV2Response{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
	}, nil
}
