// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.client;

import io.github.primelib.komga.client.models.AuthorDto;
import io.github.primelib.komga.client.models.PageAuthorDto;
import io.github.primelib.komga.client.operations.GetAgeRatingsV1OperationSpec;
import io.github.primelib.komga.client.operations.GetAuthorsNamesV1OperationSpec;
import io.github.primelib.komga.client.operations.GetAuthorsV1OperationSpec;
import io.github.primelib.komga.client.operations.GetAuthorsV2OperationSpec;
import io.github.primelib.komga.client.operations.GetGenresV1OperationSpec;
import io.github.primelib.komga.client.operations.GetLanguagesV1OperationSpec;
import io.github.primelib.komga.client.operations.GetPublishersV1OperationSpec;
import io.github.primelib.komga.client.operations.GetSeriesReleaseDatesV1OperationSpec;
import io.github.primelib.komga.client.operations.GetSharingLabelsV1OperationSpec;
import io.github.primelib.komga.client.operations.GetTagsBookV1OperationSpec;
import io.github.primelib.komga.client.operations.GetTagsSeriesV1OperationSpec;
import io.github.primelib.komga.client.operations.GetTagsV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * KomgaClientreferentialControllerConsumerApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public class KomgaClientreferentialControllerConsumerApi {
    private final KomgaClientreferentialControllerApi api;

    public KomgaClientreferentialControllerConsumerApi(KomgaClientreferentialControllerApi api) {
        this.api = api;
    }


    /**
    * GetAuthorsV2
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>search: </li>
    *   <li>role: </li>
    *   <li>libraryId: </li>
    *   <li>collectionId: </li>
    *   <li>seriesId: </li>
    *   <li>readlistId: </li>
    *   <li>unpaged: </li>
    *   <li>page: Zero-based page index (0..N)</li>
    *   <li>size: The size of the page to be returned</li>
    * </ul>
    */
    public PageAuthorDto GetAuthorsV2(Consumer<GetAuthorsV2OperationSpec> spec) {
        GetAuthorsV2OperationSpec r = new GetAuthorsV2OperationSpec(spec);
        return api.GetAuthorsV2(r.search(), r.role(), r.libraryId(), r.collectionId(), r.seriesId(), r.readlistId(), r.unpaged(), r.page(), r.size());
    }

    /**
    * GetTagsV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>libraryId: </li>
    *   <li>collectionId: </li>
    * </ul>
    */
    public String[] GetTagsV1(Consumer<GetTagsV1OperationSpec> spec) {
        GetTagsV1OperationSpec r = new GetTagsV1OperationSpec(spec);
        return api.GetTagsV1(r.libraryId(), r.collectionId());
    }

    /**
    * GetTagsSeriesV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>libraryId: </li>
    *   <li>collectionId: </li>
    * </ul>
    */
    public String[] GetTagsSeriesV1(Consumer<GetTagsSeriesV1OperationSpec> spec) {
        GetTagsSeriesV1OperationSpec r = new GetTagsSeriesV1OperationSpec(spec);
        return api.GetTagsSeriesV1(r.libraryId(), r.collectionId());
    }

    /**
    * GetTagsBookV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>seriesId: </li>
    *   <li>readlistId: </li>
    * </ul>
    */
    public String[] GetTagsBookV1(Consumer<GetTagsBookV1OperationSpec> spec) {
        GetTagsBookV1OperationSpec r = new GetTagsBookV1OperationSpec(spec);
        return api.GetTagsBookV1(r.seriesId(), r.readlistId());
    }

    /**
    * GetSharingLabelsV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>libraryId: </li>
    *   <li>collectionId: </li>
    * </ul>
    */
    public String[] GetSharingLabelsV1(Consumer<GetSharingLabelsV1OperationSpec> spec) {
        GetSharingLabelsV1OperationSpec r = new GetSharingLabelsV1OperationSpec(spec);
        return api.GetSharingLabelsV1(r.libraryId(), r.collectionId());
    }

    /**
    * GetSeriesReleaseDatesV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>libraryId: </li>
    *   <li>collectionId: </li>
    * </ul>
    */
    public String[] GetSeriesReleaseDatesV1(Consumer<GetSeriesReleaseDatesV1OperationSpec> spec) {
        GetSeriesReleaseDatesV1OperationSpec r = new GetSeriesReleaseDatesV1OperationSpec(spec);
        return api.GetSeriesReleaseDatesV1(r.libraryId(), r.collectionId());
    }

    /**
    * GetPublishersV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>libraryId: </li>
    *   <li>collectionId: </li>
    * </ul>
    */
    public String[] GetPublishersV1(Consumer<GetPublishersV1OperationSpec> spec) {
        GetPublishersV1OperationSpec r = new GetPublishersV1OperationSpec(spec);
        return api.GetPublishersV1(r.libraryId(), r.collectionId());
    }

    /**
    * GetLanguagesV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>libraryId: </li>
    *   <li>collectionId: </li>
    * </ul>
    */
    public String[] GetLanguagesV1(Consumer<GetLanguagesV1OperationSpec> spec) {
        GetLanguagesV1OperationSpec r = new GetLanguagesV1OperationSpec(spec);
        return api.GetLanguagesV1(r.libraryId(), r.collectionId());
    }

    /**
    * GetGenresV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>libraryId: </li>
    *   <li>collectionId: </li>
    * </ul>
    */
    public String[] GetGenresV1(Consumer<GetGenresV1OperationSpec> spec) {
        GetGenresV1OperationSpec r = new GetGenresV1OperationSpec(spec);
        return api.GetGenresV1(r.libraryId(), r.collectionId());
    }

    /**
    * GetAuthorsV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>search: </li>
    *   <li>libraryId: </li>
    *   <li>collectionId: </li>
    *   <li>seriesId: </li>
    * </ul>
    */
    public AuthorDto[] GetAuthorsV1(Consumer<GetAuthorsV1OperationSpec> spec) {
        GetAuthorsV1OperationSpec r = new GetAuthorsV1OperationSpec(spec);
        return api.GetAuthorsV1(r.search(), r.libraryId(), r.collectionId(), r.seriesId());
    }

    /**
    * GetAuthorsRolesV1
    * 
    *
    */
    public String[] GetAuthorsRolesV1() {
        return api.GetAuthorsRolesV1();
    }

    /**
    * GetAuthorsNamesV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>search: </li>
    * </ul>
    */
    public String[] GetAuthorsNamesV1(Consumer<GetAuthorsNamesV1OperationSpec> spec) {
        GetAuthorsNamesV1OperationSpec r = new GetAuthorsNamesV1OperationSpec(spec);
        return api.GetAuthorsNamesV1(r.search());
    }

    /**
    * GetAgeRatingsV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>libraryId: </li>
    *   <li>collectionId: </li>
    * </ul>
    */
    public String[] GetAgeRatingsV1(Consumer<GetAgeRatingsV1OperationSpec> spec) {
        GetAgeRatingsV1OperationSpec r = new GetAgeRatingsV1OperationSpec(spec);
        return api.GetAgeRatingsV1(r.libraryId(), r.collectionId());
    }

}
