// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.client;

import feign.Param;
import feign.RequestLine;
import io.github.primelib.komga.client.models.OpdsFeed;
import io.github.primelib.komga.client.models.OpenSearchDescription;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * KomgaClientopdsControllerApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface KomgaClientopdsControllerApi {

    /**
    * GetOpdsV12SeriesV1
    * 
    *
    * @param search 
    * @param publisher 
    * @param page Zero-based page index (0..N)
    */
    @RequestLine("GET /opds/v1.2/series?search={search}&publisher={publisher}&page={page}")
    OpdsFeed GetOpdsV12SeriesV1(
            @Nullable @Param("search") String search,
            @Nullable @Param("publisher") String[] publisher,
            @Nullable @Param("page") Integer page
    );

    /**
    * GetOpdsV12SeriesByIDV1
    * 
    *
    * @param id 
    * @param page Zero-based page index (0..N)
    */
    @RequestLine("GET /opds/v1.2/series/{id}?page={page}")
    OpdsFeed GetOpdsV12SeriesByIDV1(
            @NotNull @Param("id") String id,
            @Nullable @Param("page") Integer page
    );

    /**
    * GetOpdsV12SeriesLatestV1
    * 
    *
    * @param page Zero-based page index (0..N)
    */
    @RequestLine("GET /opds/v1.2/series/latest?page={page}")
    OpdsFeed GetOpdsV12SeriesLatestV1(
            @Nullable @Param("page") Integer page
    );

    /**
    * GetOpdsV12SearchV1
    * 
    *
    */
    @RequestLine("GET /opds/v1.2/search")
    OpenSearchDescription GetOpdsV12SearchV1();

    /**
    * GetOpdsV12ReadlistsV1
    * 
    *
    * @param page Zero-based page index (0..N)
    */
    @RequestLine("GET /opds/v1.2/readlists?page={page}")
    OpdsFeed GetOpdsV12ReadlistsV1(
            @Nullable @Param("page") Integer page
    );

    /**
    * GetOpdsV12ReadlistByIDV1
    * 
    *
    * @param id 
    * @param page Zero-based page index (0..N)
    */
    @RequestLine("GET /opds/v1.2/readlists/{id}?page={page}")
    OpdsFeed GetOpdsV12ReadlistByIDV1(
            @NotNull @Param("id") String id,
            @Nullable @Param("page") Integer page
    );

    /**
    * GetOpdsV12PublishersV1
    * 
    *
    * @param page Zero-based page index (0..N)
    */
    @RequestLine("GET /opds/v1.2/publishers?page={page}")
    OpdsFeed GetOpdsV12PublishersV1(
            @Nullable @Param("page") Integer page
    );

    /**
    * GetOpdsV12OndeckV1
    * 
    *
    * @param page Zero-based page index (0..N)
    */
    @RequestLine("GET /opds/v1.2/ondeck?page={page}")
    OpdsFeed GetOpdsV12OndeckV1(
            @Nullable @Param("page") Integer page
    );

    /**
    * GetOpdsV12LibrariesV1
    * 
    *
    */
    @RequestLine("GET /opds/v1.2/libraries")
    OpdsFeed GetOpdsV12LibrariesV1();

    /**
    * GetOpdsV12LibraryByIDV1
    * 
    *
    * @param id 
    * @param page Zero-based page index (0..N)
    */
    @RequestLine("GET /opds/v1.2/libraries/{id}?page={page}")
    OpdsFeed GetOpdsV12LibraryByIDV1(
            @NotNull @Param("id") String id,
            @Nullable @Param("page") Integer page
    );

    /**
    * GetOpdsV12KeepReadingV1
    * 
    *
    * @param page Zero-based page index (0..N)
    */
    @RequestLine("GET /opds/v1.2/keep-reading?page={page}")
    OpdsFeed GetOpdsV12KeepReadingV1(
            @Nullable @Param("page") Integer page
    );

    /**
    * GetOpdsV12CollectionsV1
    * 
    *
    * @param page Zero-based page index (0..N)
    */
    @RequestLine("GET /opds/v1.2/collections?page={page}")
    OpdsFeed GetOpdsV12CollectionsV1(
            @Nullable @Param("page") Integer page
    );

    /**
    * GetOpdsV12CollectionByIDV1
    * 
    *
    * @param id 
    * @param page Zero-based page index (0..N)
    */
    @RequestLine("GET /opds/v1.2/collections/{id}?page={page}")
    OpdsFeed GetOpdsV12CollectionByIDV1(
            @NotNull @Param("id") String id,
            @Nullable @Param("page") Integer page
    );

    /**
    * GetOpdsV12CatalogV1
    * 
    *
    */
    @RequestLine("GET /opds/v1.2/catalog")
    OpdsFeed GetOpdsV12CatalogV1();

    /**
    * GetOpdsV12BookByBookIDThumbnailSmallV1
    * 
    *
    * @param bookId 
    */
    @RequestLine("GET /opds/v1.2/books/{bookId}/thumbnail/small")
    void GetOpdsV12BookByBookIDThumbnailSmallV1(
            @NotNull @Param("bookId") String bookId
    );

    /**
    * GetOpdsV12BooksLatestV1
    * 
    *
    * @param page Zero-based page index (0..N)
    */
    @RequestLine("GET /opds/v1.2/books/latest?page={page}")
    OpdsFeed GetOpdsV12BooksLatestV1(
            @Nullable @Param("page") Integer page
    );

}
