// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.client;

import io.github.primelib.komga.client.models.TransientBookDto;
import io.github.primelib.komga.client.operations.GetTransientBookByIDPageByPageNumberV1OperationSpec;
import io.github.primelib.komga.client.operations.PostTransientBookByIDAnalyzeV1OperationSpec;
import io.github.primelib.komga.client.operations.PostTransientBooksV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * KomgaClienttransientBooksControllerConsumerApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public class KomgaClienttransientBooksControllerConsumerApi {
    private final KomgaClienttransientBooksControllerApi api;

    public KomgaClienttransientBooksControllerConsumerApi(KomgaClienttransientBooksControllerApi api) {
        this.api = api;
    }


    /**
    * PostTransientBooksV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: </li>
    * </ul>
    */
    public TransientBookDto[] PostTransientBooksV1(Consumer<PostTransientBooksV1OperationSpec> spec) {
        PostTransientBooksV1OperationSpec r = new PostTransientBooksV1OperationSpec(spec);
        return api.PostTransientBooksV1(r.payload());
    }

    /**
    * PostTransientBookByIDAnalyzeV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>id: </li>
    * </ul>
    */
    public TransientBookDto PostTransientBookByIDAnalyzeV1(Consumer<PostTransientBookByIDAnalyzeV1OperationSpec> spec) {
        PostTransientBookByIDAnalyzeV1OperationSpec r = new PostTransientBookByIDAnalyzeV1OperationSpec(spec);
        return api.PostTransientBookByIDAnalyzeV1(r.id());
    }

    /**
    * GetTransientBookByIDPageByPageNumberV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>id: </li>
    *   <li>pageNumber: </li>
    * </ul>
    */
    public Byte[] GetTransientBookByIDPageByPageNumberV1(Consumer<GetTransientBookByIDPageByPageNumberV1OperationSpec> spec) {
        GetTransientBookByIDPageByPageNumberV1OperationSpec r = new GetTransientBookByIDPageByPageNumberV1OperationSpec(spec);
        return api.GetTransientBookByIDPageByPageNumberV1(r.id(), r.pageNumber());
    }

}
