// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.client;

import feign.Headers;
import feign.RequestLine;
import io.github.primelib.komga.client.models.JsonFeedDto;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * KomgaClientannouncementControllerApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface KomgaClientannouncementControllerApi {

    /**
    * GetAnnouncementsV1
    * 
    *
    */
    @RequestLine("GET /api/v1/announcements")
    JsonFeedDto GetAnnouncementsV1();

    /**
    * PutAnnouncementsV1
    * 
    *
    * @param payload 
    */
    @RequestLine("PUT /api/v1/announcements")
    @Headers({
        "Content-Type: application/json"
    })
    void PutAnnouncementsV1(
            @NotNull String[] payload
    );

}
