// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.client;



import javax.annotation.processing.Generated;

/**
 * KomgaClientloginControllerConsumerApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public class KomgaClientloginControllerConsumerApi {
    private final KomgaClientloginControllerApi api;

    public KomgaClientloginControllerConsumerApi(KomgaClientloginControllerApi api) {
        this.api = api;
    }


    /**
    * GetLoginSetCookieV1
    * 
    *
    */
    public void GetLoginSetCookieV1() {
        api.GetLoginSetCookieV1();
    }

}
