// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.client;

import feign.Param;
import feign.RequestLine;
import io.github.primelib.komga.client.models.PageHistoricalEventDto;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.Nullable;

/**
 * KomgaClienthistoricalEventControllerApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface KomgaClienthistoricalEventControllerApi {

    /**
    * GetHistoryV1
    * 
    *
    * @param page Zero-based page index (0..N)
    * @param size The size of the page to be returned
    * @param sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
    */
    @RequestLine("GET /api/v1/history?page={page}&size={size}&sort={sort}")
    PageHistoricalEventDto GetHistoryV1(
            @Nullable @Param("page") Integer page,
            @Nullable @Param("size") Integer size,
            @Nullable @Param("sort") String[] sort
    );

}
