// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.client;

import feign.Param;
import feign.RequestLine;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * KomgaClientopdsCommonControllerApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface KomgaClientopdsCommonControllerApi {

    /**
    * GetOpdsV12BookByBookIDThumbnailV1
    * 
    *
    * @param bookId 
    */
    @RequestLine("GET /opds/v1.2/books/{bookId}/thumbnail")
    void GetOpdsV12BookByBookIDThumbnailV1(
            @NotNull @Param("bookId") String bookId
    );

    /**
    * GetOpdsbookByBookIDThumbnailV2
    * 
    *
    * @param bookId 
    */
    @RequestLine("GET /opds/v2/books/{bookId}/thumbnail")
    void GetOpdsbookByBookIDThumbnailV2(
            @NotNull @Param("bookId") String bookId
    );

}
