// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.client;

import io.github.primelib.komga.client.models.JsonFeedDto;
import io.github.primelib.komga.client.operations.PutAnnouncementsV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * KomgaClientannouncementControllerConsumerApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public class KomgaClientannouncementControllerConsumerApi {
    private final KomgaClientannouncementControllerApi api;

    public KomgaClientannouncementControllerConsumerApi(KomgaClientannouncementControllerApi api) {
        this.api = api;
    }


    /**
    * GetAnnouncementsV1
    * 
    *
    */
    public JsonFeedDto GetAnnouncementsV1() {
        return api.GetAnnouncementsV1();
    }

    /**
    * PutAnnouncementsV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: </li>
    * </ul>
    */
    public void PutAnnouncementsV1(Consumer<PutAnnouncementsV1OperationSpec> spec) {
        PutAnnouncementsV1OperationSpec r = new PutAnnouncementsV1OperationSpec(spec);
        api.PutAnnouncementsV1(r.payload());
    }

}
