// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.client;



import javax.annotation.processing.Generated;

/**
 * KomgaClienttaskControllerConsumerApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public class KomgaClienttaskControllerConsumerApi {
    private final KomgaClienttaskControllerApi api;

    public KomgaClienttaskControllerConsumerApi(KomgaClienttaskControllerApi api) {
        this.api = api;
    }


    /**
    * DeleteTasksV1
    * 
    *
    */
    public Integer DeleteTasksV1() {
        return api.DeleteTasksV1();
    }

}
