// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.client;

import io.github.primelib.komga.client.models.SettingsDto;
import io.github.primelib.komga.client.operations.PatchSettingsV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * KomgaClientsettingsControllerConsumerApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public class KomgaClientsettingsControllerConsumerApi {
    private final KomgaClientsettingsControllerApi api;

    public KomgaClientsettingsControllerConsumerApi(KomgaClientsettingsControllerApi api) {
        this.api = api;
    }


    /**
    * GetSettingsV1
    * 
    *
    */
    public SettingsDto GetSettingsV1() {
        return api.GetSettingsV1();
    }

    /**
    * PatchSettingsV1
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: </li>
    * </ul>
    */
    public void PatchSettingsV1(Consumer<PatchSettingsV1OperationSpec> spec) {
        PatchSettingsV1OperationSpec r = new PatchSettingsV1OperationSpec(spec);
        api.PatchSettingsV1(r.payload());
    }

}
