// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type AuthorUpdateDto struct {
	Name *string `json:"name" form:"name=name"`
	Role *string `json:"role" form:"name=role"`
}
