// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// BookMetadataUpdateDto Metadata fields to update. Set a field to null to unset the metadata. You can omit fields you don't want to update.

type BookMetadataUpdateDto struct {
	Title           *string             `json:"title" form:"name=title"`
	TitleLock       *bool               `json:"titleLock" form:"name=titleLock"`
	SummaryLock     *bool               `json:"summaryLock" form:"name=summaryLock"`
	Number          *string             `json:"number" form:"name=number"`
	NumberLock      *bool               `json:"numberLock" form:"name=numberLock"`
	NumberSort      *float32            `json:"numberSort" form:"name=numberSort"`
	NumberSortLock  *bool               `json:"numberSortLock" form:"name=numberSortLock"`
	ReleaseDateLock *bool               `json:"releaseDateLock" form:"name=releaseDateLock"`
	AuthorsLock     *bool               `json:"authorsLock" form:"name=authorsLock"`
	TagsLock        *bool               `json:"tagsLock" form:"name=tagsLock"`
	IsbnLock        *bool               `json:"isbnLock" form:"name=isbnLock"`
	LinksLock       *bool               `json:"linksLock" form:"name=linksLock"`
	Tags            []*string           `json:"tags" form:"name=tags,json"`
	Isbn            *string             `json:"isbn" form:"name=isbn"`
	Links           []*WebLinkUpdateDto `json:"links" form:"name=links,json"`
	Authors         []*AuthorUpdateDto  `json:"authors" form:"name=authors,json"`
	Summary         *string             `json:"summary" form:"name=summary"`
	ReleaseDate     *string             `json:"releaseDate" form:"name=releaseDate"`
}
