// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type BookImportBatchDto struct {
	Books    []*BookImportDto `json:"books" form:"name=books,json"`
	CopyMode *string          `json:"copyMode" form:"name=copyMode"`
}
