// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type DirectoryListingDto struct {
	Parent      *string    `json:"parent" form:"name=parent"`
	Directories []*PathDto `json:"directories" form:"name=directories,json"`
}
