// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type JsonFeedDto struct {
	Version     *string    `json:"version" form:"name=version"`
	Title       *string    `json:"title" form:"name=title"`
	HomePageUrl *string    `json:"home_page_url" form:"name=home_page_url"`
	Description *string    `json:"description" form:"name=description"`
	Items       []*ItemDto `json:"items" form:"name=items,json"`
}
