// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// LibraryUpdateDto Fields to update. You can omit fields you don't want to update.

type LibraryUpdateDto struct {
	Name                              *string   `json:"name" form:"name=name"`
	Root                              *string   `json:"root" form:"name=root"`
	ImportComicInfoBook               *bool     `json:"importComicInfoBook" form:"name=importComicInfoBook"`
	ImportComicInfoSeries             *bool     `json:"importComicInfoSeries" form:"name=importComicInfoSeries"`
	ImportComicInfoCollection         *bool     `json:"importComicInfoCollection" form:"name=importComicInfoCollection"`
	ImportComicInfoReadList           *bool     `json:"importComicInfoReadList" form:"name=importComicInfoReadList"`
	ImportComicInfoSeriesAppendVolume *bool     `json:"importComicInfoSeriesAppendVolume" form:"name=importComicInfoSeriesAppendVolume"`
	ImportEpubBook                    *bool     `json:"importEpubBook" form:"name=importEpubBook"`
	ImportEpubSeries                  *bool     `json:"importEpubSeries" form:"name=importEpubSeries"`
	ImportMylarSeries                 *bool     `json:"importMylarSeries" form:"name=importMylarSeries"`
	ImportLocalArtwork                *bool     `json:"importLocalArtwork" form:"name=importLocalArtwork"`
	ImportBarcodeIsbn                 *bool     `json:"importBarcodeIsbn" form:"name=importBarcodeIsbn"`
	ScanForceModifiedTime             *bool     `json:"scanForceModifiedTime" form:"name=scanForceModifiedTime"`
	ScanInterval                      *string   `json:"scanInterval" form:"name=scanInterval"`
	ScanOnStartup                     *bool     `json:"scanOnStartup" form:"name=scanOnStartup"`
	ScanCbx                           *bool     `json:"scanCbx" form:"name=scanCbx"`
	ScanPdf                           *bool     `json:"scanPdf" form:"name=scanPdf"`
	ScanEpub                          *bool     `json:"scanEpub" form:"name=scanEpub"`
	RepairExtensions                  *bool     `json:"repairExtensions" form:"name=repairExtensions"`
	ConvertToCbz                      *bool     `json:"convertToCbz" form:"name=convertToCbz"`
	EmptyTrashAfterScan               *bool     `json:"emptyTrashAfterScan" form:"name=emptyTrashAfterScan"`
	SeriesCover                       *string   `json:"seriesCover" form:"name=seriesCover"`
	HashFiles                         *bool     `json:"hashFiles" form:"name=hashFiles"`
	HashPages                         *bool     `json:"hashPages" form:"name=hashPages"`
	AnalyzeDimensions                 *bool     `json:"analyzeDimensions" form:"name=analyzeDimensions"`
	OneshotsDirectory                 *string   `json:"oneshotsDirectory" form:"name=oneshotsDirectory"`
	ScanDirectoryExclusions           []*string `json:"scanDirectoryExclusions" form:"name=scanDirectoryExclusions,json"`
}
