// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type MediaDto struct {
	Status     *string `json:"status" form:"name=status"`
	MediaType  *string `json:"mediaType" form:"name=mediaType"`
	PagesCount *int32  `json:"pagesCount" form:"name=pagesCount"`
	Comment    *string `json:"comment" form:"name=comment"`
}
