// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type OpdsLink struct {
	Type *string `json:"type" form:"name=type"`
	Rel  *string `json:"rel" form:"name=rel"`
	Href *string `json:"href" form:"name=href"`
}
