// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type OpdsEntry struct {
	Title   *string `json:"title" form:"name=title"`
	Updated *string `json:"updated" form:"name=updated"`
	Id      *string `json:"id" form:"name=id"`
	Content *string `json:"content" form:"name=content"`
}
