// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type PageHashCreationDto struct {
	Hash   *string `json:"hash" form:"name=hash"`
	Size   *int64  `json:"size" form:"name=size"`
	Action *string `json:"action" form:"name=action"`
}
