// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// PatchBooksMetadataV1B A map of book IDs which values are the metadata fields to update. Set a field to null to unset the metadata. You can omit fields you don't want to update.
type PatchBooksMetadataV1B map[*string]*BookMetadataUpdateDto
