// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type PathDto struct {
	Type *string `json:"type" form:"name=type"`
	Name *string `json:"name" form:"name=name"`
	Path *string `json:"path" form:"name=path"`
}
