// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// ReadProgressUpdateDto page can be omitted if completed is set to true. completed can be omitted, and will be set accordingly depending on the page passed and the total number of pages in the book.

type ReadProgressUpdateDto struct {
	Page      *int32 `json:"page" form:"name=page"`
	Completed *bool  `json:"completed" form:"name=completed"`
}
