// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ReadListRequestBookDto struct {
	Series []*string `json:"series" form:"name=series,json"`
	Number *string   `json:"number" form:"name=number"`
}
