// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ReadListUpdateDto struct {
	Name    *string   `json:"name" form:"name=name"`
	Summary *string   `json:"summary" form:"name=summary"`
	BookIDS []*string `json:"bookIds" form:"name=bookIds,json"`
	Ordered *bool     `json:"ordered" form:"name=ordered"`
}
