// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// SeriesMetadataUpdateDto Metadata fields to update. Set a field to null to unset the metadata. You can omit fields you don't want to update.

type SeriesMetadataUpdateDto struct {
	Status               *string                    `json:"status" form:"name=status"`
	StatusLock           *bool                      `json:"statusLock" form:"name=statusLock"`
	Title                *string                    `json:"title" form:"name=title"`
	TitleLock            *bool                      `json:"titleLock" form:"name=titleLock"`
	TitleSort            *string                    `json:"titleSort" form:"name=titleSort"`
	TitleSortLock        *bool                      `json:"titleSortLock" form:"name=titleSortLock"`
	Summary              *string                    `json:"summary" form:"name=summary"`
	SummaryLock          *bool                      `json:"summaryLock" form:"name=summaryLock"`
	Publisher            *string                    `json:"publisher" form:"name=publisher"`
	PublisherLock        *bool                      `json:"publisherLock" form:"name=publisherLock"`
	ReadingDirectionLock *bool                      `json:"readingDirectionLock" form:"name=readingDirectionLock"`
	AgeRatingLock        *bool                      `json:"ageRatingLock" form:"name=ageRatingLock"`
	Language             *string                    `json:"language" form:"name=language"`
	LanguageLock         *bool                      `json:"languageLock" form:"name=languageLock"`
	GenresLock           *bool                      `json:"genresLock" form:"name=genresLock"`
	TagsLock             *bool                      `json:"tagsLock" form:"name=tagsLock"`
	TotalBookCountLock   *bool                      `json:"totalBookCountLock" form:"name=totalBookCountLock"`
	SharingLabelsLock    *bool                      `json:"sharingLabelsLock" form:"name=sharingLabelsLock"`
	LinksLock            *bool                      `json:"linksLock" form:"name=linksLock"`
	AlternateTitlesLock  *bool                      `json:"alternateTitlesLock" form:"name=alternateTitlesLock"`
	Tags                 []*string                  `json:"tags" form:"name=tags,json"`
	Links                []*WebLinkUpdateDto        `json:"links" form:"name=links,json"`
	ReadingDirection     *string                    `json:"readingDirection" form:"name=readingDirection"`
	AgeRating            *int32                     `json:"ageRating" form:"name=ageRating"`
	Genres               []*string                  `json:"genres" form:"name=genres,json"`
	TotalBookCount       *int32                     `json:"totalBookCount" form:"name=totalBookCount"`
	SharingLabels        []*string                  `json:"sharingLabels" form:"name=sharingLabels,json"`
	AlternateTitles      []*AlternateTitleUpdateDto `json:"alternateTitles" form:"name=alternateTitles,json"`
}
