// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type SeriesDto struct {
	Id                   *string                     `json:"id" form:"name=id"`
	LibraryId            *string                     `json:"libraryId" form:"name=libraryId"`
	Name                 *string                     `json:"name" form:"name=name"`
	Url                  *string                     `json:"url" form:"name=url"`
	Created              *string                     `json:"created" form:"name=created"`
	LastModified         *string                     `json:"lastModified" form:"name=lastModified"`
	FileLastModified     *string                     `json:"fileLastModified" form:"name=fileLastModified"`
	BooksCount           *int32                      `json:"booksCount" form:"name=booksCount"`
	BooksReadCount       *int32                      `json:"booksReadCount" form:"name=booksReadCount"`
	BooksUnreadCount     *int32                      `json:"booksUnreadCount" form:"name=booksUnreadCount"`
	BooksInProgressCount *int32                      `json:"booksInProgressCount" form:"name=booksInProgressCount"`
	Metadata             *SeriesMetadataDto          `json:"metadata" form:"name=metadata,json"`
	BooksMetadata        *BookMetadataAggregationDto `json:"booksMetadata" form:"name=booksMetadata,json"`
	Deleted              *bool                       `json:"deleted" form:"name=deleted"`
	Oneshot              *bool                       `json:"oneshot" form:"name=oneshot"`
}
