// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type SettingsDto struct {
	DeleteEmptyCollections *bool   `json:"deleteEmptyCollections" form:"name=deleteEmptyCollections"`
	DeleteEmptyReadLists   *bool   `json:"deleteEmptyReadLists" form:"name=deleteEmptyReadLists"`
	RememberMeDurationDays *int64  `json:"rememberMeDurationDays" form:"name=rememberMeDurationDays"`
	ThumbnailSize          *string `json:"thumbnailSize" form:"name=thumbnailSize"`
	TaskPoolSize           *int32  `json:"taskPoolSize" form:"name=taskPoolSize"`
}
