// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type TachiyomiReadProgressDto struct {
	BooksCount              *int32 `json:"booksCount" form:"name=booksCount"`
	BooksReadCount          *int32 `json:"booksReadCount" form:"name=booksReadCount"`
	BooksUnreadCount        *int32 `json:"booksUnreadCount" form:"name=booksUnreadCount"`
	BooksInProgressCount    *int32 `json:"booksInProgressCount" form:"name=booksInProgressCount"`
	LastReadContinuousIndex *int32 `json:"lastReadContinuousIndex" form:"name=lastReadContinuousIndex"`
}
