// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type TachiyomiReadProgressV2Dto struct {
	BooksCount                   *int32   `json:"booksCount" form:"name=booksCount"`
	BooksReadCount               *int32   `json:"booksReadCount" form:"name=booksReadCount"`
	BooksUnreadCount             *int32   `json:"booksUnreadCount" form:"name=booksUnreadCount"`
	BooksInProgressCount         *int32   `json:"booksInProgressCount" form:"name=booksInProgressCount"`
	LastReadContinuousNumberSort *float32 `json:"lastReadContinuousNumberSort" form:"name=lastReadContinuousNumberSort"`
	MaxNumberSort                *float32 `json:"maxNumberSort" form:"name=maxNumberSort"`
}
