// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type TransientBookDto struct {
	Id               *string    `json:"id" form:"name=id"`
	Name             *string    `json:"name" form:"name=name"`
	Url              *string    `json:"url" form:"name=url"`
	FileLastModified *string    `json:"fileLastModified" form:"name=fileLastModified"`
	SizeBytes        *int64     `json:"sizeBytes" form:"name=sizeBytes"`
	Size             *string    `json:"size" form:"name=size"`
	Status           *string    `json:"status" form:"name=status"`
	MediaType        *string    `json:"mediaType" form:"name=mediaType"`
	Pages            []*PageDto `json:"pages" form:"name=pages,json"`
	Files            []*string  `json:"files" form:"name=files,json"`
	Comment          *string    `json:"comment" form:"name=comment"`
}
