// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type UserUpdateDto struct {
	Roles           []*string                 `json:"roles" form:"name=roles,json"`
	LabelsAllow     []*string                 `json:"labelsAllow" form:"name=labelsAllow,json"`
	LabelsExclude   []*string                 `json:"labelsExclude" form:"name=labelsExclude,json"`
	AgeRestriction  *AgeRestrictionUpdateDto  `json:"ageRestriction" form:"name=ageRestriction,json"`
	SharedLibraries *SharedLibrariesUpdateDto `json:"sharedLibraries" form:"name=sharedLibraries,json"`
}
