// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type UserCreationDto struct {
	Email    *string   `json:"email" form:"name=email"`
	Password *string   `json:"password" form:"name=password"`
	Roles    []*string `json:"roles" form:"name=roles,json"`
}
