// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type WebLinkUpdateDto struct {
	Label *string `json:"label" form:"name=label"`
	Url   *string `json:"url" form:"name=url"`
}
