// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package enums

type ActionEnum string

const (
	ActionEnumDeleteAuto   ActionEnum = "DELETE_AUTO"
	ActionEnumDeleteManual ActionEnum = "DELETE_MANUAL"
	ActionEnumIgnore       ActionEnum = "IGNORE"
)

func (e ActionEnum) ToPointer() *ActionEnum {
	return &e
}
