// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package enums

type RestrictionEnum string

const (
	RestrictionEnumAllowOnly RestrictionEnum = "ALLOW_ONLY"
	RestrictionEnumExclude   RestrictionEnum = "EXCLUDE"
)

func (e RestrictionEnum) ToPointer() *RestrictionEnum {
	return &e
}
