// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package enums

type SeriesCoverEnum string

const (
	SeriesCoverEnumFirst              SeriesCoverEnum = "FIRST"
	SeriesCoverEnumFirstUnreadOrFirst SeriesCoverEnum = "FIRST_UNREAD_OR_FIRST"
	SeriesCoverEnumFirstUnreadOrLast  SeriesCoverEnum = "FIRST_UNREAD_OR_LAST"
	SeriesCoverEnumLast               SeriesCoverEnum = "LAST"
)

func (e SeriesCoverEnum) ToPointer() *SeriesCoverEnum {
	return &e
}
