// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package enums

type StatusEnum string

const (
	StatusEnumAbandoned StatusEnum = "ABANDONED"
	StatusEnumEnded     StatusEnum = "ENDED"
	StatusEnumHiatus    StatusEnum = "HIATUS"
	StatusEnumOngoing   StatusEnum = "ONGOING"
)

func (e StatusEnum) ToPointer() *StatusEnum {
	return &e
}
