// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.komga.client.operations;

import io.github.primelib.komga.client.models.MediaType;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * GetBookByBookIDPageByPageNumberV1
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class GetBookByBookIDPageByPageNumberV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * 
     */
    // TODO: annotations
    private String bookId;

    /**
     * 
     */
    // TODO: annotations
    private Integer pageNumber;

    /**
     * Convert the image to the provided format.
     */
    // TODO: annotations
    private String convert;

    /**
     * If set to true, pages will start at index 0. If set to false, pages will start at index 1.
     */
    // TODO: annotations
    private Boolean zeroBased;

    /**
     * Some very limited server driven content negotiation is handled. If a book is a PDF book, and the Accept header contains 'application/pdf' as a more specific type than other 'image/' types, a raw PDF page will be returned.
     */
    // TODO: annotations
    private MediaType[] accept;

    /**
     * Constructs a validated instance of {@link GetBookByBookIDPageByPageNumberV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public GetBookByBookIDPageByPageNumberV1OperationSpec(Consumer<GetBookByBookIDPageByPageNumberV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(bookId, "bookId is a required parameter!");
        Objects.requireNonNull(pageNumber, "pageNumber is a required parameter!");
    }
}
